package org.gtlcore.gtlcore.integration.ae2.graph.core;

import java.util.*;

/** Ready queue for a proven acyclic flat witness; cyclic stages keep their serial barriers. */
final class DagScheduler<K> {

    private final List<PlanStep.Batch> steps;
    private final long[] remaining;
    private final boolean[] queued;
    private final long[] generation;
    private final Deque<Integer> ready = new ArrayDeque<>();
    private final PriorityQueue<Retry> retries = new PriorityQueue<>(Comparator.comparingLong(Retry::tick));
    private final Map<K, List<Integer>> consumers = new HashMap<>();
    private int unfinished;
    private int active = -1;

    private DagScheduler(List<PlanStep.Batch> steps, Map<String, GraphRecipe<K>> recipes, Map<String, Long> accepted) {
        this.steps = List.copyOf(steps);
        remaining = new long[steps.size()];
        queued = new boolean[steps.size()];
        generation = new long[steps.size()];
        for (int i = 0; i < steps.size(); i++) {
            PlanStep.Batch step = steps.get(i);
            remaining[i] = step.runs() - accepted.getOrDefault(step.recipe(), 0L);
            if (remaining[i] < 0) throw new IllegalArgumentException("DAG accepted count exceeds plan");
            if (remaining[i] > 0) {
                unfinished++;
                enqueue(i);
            }
            for (K key : recipes.get(step.recipe()).inputs().keySet()) consumers.computeIfAbsent(key, ignored -> new ArrayList<>()).add(i);
        }
    }

    static <K> DagScheduler<K> create(GraphPlan<K> plan, Map<String, Long> accepted) {
        if (!(plan.steps() instanceof PlanStep.Sequence sequence) || !plan.seeds().isEmpty()) return null;
        List<PlanStep.Batch> steps = new ArrayList<>();
        Set<String> unique = new HashSet<>();
        Map<K, Integer> lastProducer = new HashMap<>();
        for (PlanStep step : sequence.children()) {
            if (!(step instanceof PlanStep.Batch batch) || !unique.add(batch.recipe())) return null;
            int index = steps.size();
            steps.add(batch);
            for (K output : plan.recipes().get(batch.recipe()).outputs().keySet()) lastProducer.put(output, index);
        }
        for (int i = 0; i < steps.size(); i++) {
            for (K input : plan.recipes().get(steps.get(i).recipe()).inputs().keySet()) {
                // No resource can be regenerated by this or any later operation.
                // Thus arbitrary ready-node dispatch cannot steal a cyclic seed.
                if (lastProducer.getOrDefault(input, -1) >= i) return null;
            }
        }
        return new DagScheduler<>(steps, plan.recipes(), accepted);
    }

    PlanStep.Batch poll(long tick) {
        while (!retries.isEmpty() && retries.peek().tick <= tick) {
            Retry retry = retries.remove();
            if (generation[retry.index] == retry.generation) enqueue(retry.index);
        }
        if (ready.isEmpty()) {
            active = -1;
            return null;
        }
        active = ready.removeFirst();
        queued[active] = false;
        return new PlanStep.Batch(steps.get(active).recipe(), remaining[active]);
    }

    void accepted(long runs) {
        if (active < 0 || runs <= 0 || runs > remaining[active]) throw new IllegalArgumentException("No prepared DAG batch");
        remaining[active] -= runs;
        if (remaining[active] == 0) unfinished--;
        else enqueue(active);
    }

    void retry(long tick) {
        if (active >= 0) retries.add(new Retry(active, tick, ++generation[active]));
    }

    void resourceChanged(K key) {
        for (int index : consumers.getOrDefault(key, List.of())) enqueue(index);
    }

    private void enqueue(int index) {
        if (remaining[index] <= 0 || queued[index]) return;
        generation[index]++;
        queued[index] = true;
        ready.addLast(index);
    }

    boolean finished() {
        return unfinished == 0;
    }

    private record Retry(int index, long tick, long generation) {}
}
