package org.cgse.core;
import java.math.*;import java.util.*;import java.nio.file.*;
public class SymmetryOracle {
 static final BigInteger Z=BigInteger.ZERO,O=BigInteger.ONE;
 static boolean valid(List<ExactLinearProgram.Constraint> rows,BigInteger[] x){for(var r:rows){var s=Z;for(var e:r.terms().entrySet())s=s.add(e.getValue().multiply(x[e.getKey()]));if(s.compareTo(r.upper())>0)return false;}return true;}
 public static void main(String[]args)throws Exception{Files.createDirectories(Path.of("build/test-artifacts/algorithm-review"));
var rng=new Random(292894);int sat=0,unsat=0,proofs=0;
 for(int sample=0;sample<2000;sample++){int n=2+rng.nextInt(7);var rows=new ArrayList<ExactLinearProgram.Constraint>();int period=1+rng.nextInt(n);for(int r=0;r<2+rng.nextInt(7);r++){var base=new TreeMap<Integer,BigInteger>();for(int i=0;i<n;i++){int c=rng.nextInt(5)-2;if(c!=0)base.put(i,BigInteger.valueOf(c));}var bound=BigInteger.valueOf(rng.nextInt(7)-2);for(int shift=0;shift<n;shift++){var terms=new TreeMap<Integer,BigInteger>();for(var e:base.entrySet())terms.put((e.getKey()+shift)%n,e.getValue());rows.add(new ExactLinearProgram.Constraint(terms,bound));}}
 boolean possible=false;for(int mask=0;mask<(1<<n);mask++){BigInteger[] x=new BigInteger[n];for(int i=0;i<n;i++)x[i]=BigInteger.valueOf((mask>>i)&1);possible|=valid(rows,x);}var b=new PlanningBudget(0,20000000,256L<<20,()->false,System::nanoTime);var journal=new CountProof.Journal(64L<<20);b.proofJournal(journal);BigInteger[] low=new BigInteger[n],high=new BigInteger[n];Arrays.fill(low,Z);Arrays.fill(high,O);try(var search=new CountSymmetry(rows,low,high,b,1000000)){while(!search.step()){}if(search.counts()!=null){sat++;if(!possible||!valid(rows,search.counts()))throw new AssertionError("bad witness");}else if(search.infeasible()){unsat++;if(possible)throw new AssertionError("false UNSAT");}}
 for(var p:journal.symmetries()){proofs++;if(CountProof.verify(p,20000000)!=CountProof.Verdict.VERIFIED)throw new AssertionError("bad proof");var bad=new ArrayList<>(p.permutations());var badFirst=new ArrayList<>(bad.get(0));badFirst.set(0,badFirst.get(1));bad.set(0,badFirst);if(CountProof.verify(new CountProof.Symmetry(p.scope(),p.variables(),p.axioms(),bad,p.leaders()),20000000)!=CountProof.Verdict.INVALID)throw new AssertionError("tamper");}
 if(sample==0){Path file=Path.of("build/test-artifacts/algorithm-review/symmetry.cgp");journal.write(file);var loaded=CountProof.read(file);if(!journal.symmetries().equals(loaded.symmetries()))throw new AssertionError("round trip");CountProof.main(new String[]{file.toString()});}
 if(b.reservedBytes()!=0)throw new AssertionError("leak");}
 if(sat==0||unsat==0||proofs==0)throw new AssertionError("unexercised");System.out.println("PASS symmetry models=2000 SAT="+sat+" UNSAT="+unsat+" independently checked transformations="+proofs+" plus tamper and CGP9 archive");}
}
