package org.cgse.core;
import com.google.gson.*;
import java.nio.file.*;
import java.io.*;
import java.util.*;
public final class MinimizeSubset {
 static MixedSweep.Data manual;static GraphCompiler<String> original;static Set<String> manualIds;static JsonObject config,request;static BufferedWriter log;static int trials;
 static GraphCompiler<String> compiler(List<GraphRecipe<String>> extra){
  var ids=new HashSet<>(manualIds);extra.forEach(r->ids.add(r.id()));var recipes=original.catalog().stream().filter(r->ids.contains(r.id())).toList();var keys=new LinkedHashSet<String>();recipes.forEach(r->keys.addAll(r.executionOutputs().keySet()));var producers=new LinkedHashMap<String,List<GraphRecipe<String>>>();for(String key:keys)producers.put(key,original.producers(key).stream().filter(r->ids.contains(r.id())).toList());return new GraphCompiler<>(recipes,producers);
 }
 static boolean bad(List<GraphRecipe<String>> extra)throws Exception{
  var row=MixedSweep.solve(manual,compiler(extra),config,request);row.addProperty("trial",++trials);row.addProperty("extra_patterns",extra.size());log.write(MixedSweep.JSON.toJson(row));log.newLine();log.flush();if(row.get("result").getAsString().equals("ERROR"))throw new AssertionError(row);boolean result=!row.get("feasible").getAsBoolean();System.out.println("trial="+trials+" extras="+extra.size()+" bad="+result+" result="+row.get("result")+" work="+row.get("work"));return result;
 }
 public static void main(String[] args)throws Exception{
  Path base=Path.of(args[0]),out=Path.of(args[3]);Files.createDirectories(out);manual=MixedSweep.read(base.resolve("manual.json"));var extra=MixedSweep.read(base.resolve("extra-virtual.json"));config=JsonParser.parseString(Files.readString(Path.of(args[1]))).getAsJsonObject();String id=args[2];request=null;for(var r:config.getAsJsonArray("requests"))if(r.getAsJsonObject().get("id").getAsString().equals(id))request=r.getAsJsonObject();if(request==null)throw new AssertionError("Unknown request");config.remove("requests");config.addProperty("fallback",false);request.addProperty("dump",true);
  original=ParallelSubsetSweep.compiler(manual,extra,config);manualIds=new HashSet<>();manual.recipes().forEach(r->manualIds.add(r.id()));String target=request.get("target").getAsString();long amount=request.get("amount").getAsLong();
  var b=new PlanningBudget(0,20_000_000,128L<<20,()->false,System::nanoTime);GraphPlan<String> witness;var work=new CatalystPlanningWork<String>(new CatalystPolicy(4096,64),b,p->new GraphPlanningWork<>(new GraphCompiler<>(manual.recipes(),manual.producers()),target,amount,manual.stock(),manual.external(),Map.of(),true,true,b).catalysts(p));try{while(!work.step()){}witness=work.result();}finally{work.close();}if(!witness.feasible())throw new AssertionError("Baseline witness absent");PlanVerifier.verify(witness);PlanVerifier.verifyRuntimeInventory(witness);
  var known=new JsonObject();known.add("request",request);known.add("stock",MixedSweep.JSON.toJsonTree(manual.stock()));known.add("initial",MixedSweep.JSON.toJsonTree(witness.initialExact()));known.add("counts",MixedSweep.JSON.toJsonTree(witness.patternTimesExact()));known.add("steps",MixedSweep.JSON.toJsonTree(witness.steps()));var used=new JsonArray();witness.recipes().values().forEach(r->used.add(MinimizeStress.recipe(r)));known.add("recipes",used);Files.writeString(out.resolve("known-witness.json"),MixedSweep.JSON.toJson(known));
  try(var writer=Files.newBufferedWriter(out.resolve("minimize.jsonl"))){log=writer;var current=new ArrayList<>(original.catalog().stream().filter(r->!manualIds.contains(r.id())).toList());if(!bad(current)||!bad(current))throw new AssertionError("Cold failure unstable");int parts=2;
   while(!current.isEmpty()&&trials<140){int width=(current.size()+parts-1)/parts;boolean reduced=false;for(int start=0;start<current.size()&&trials<140;start+=width){var candidate=new ArrayList<>(current);candidate.subList(start,Math.min(current.size(),start+width)).clear();if(bad(candidate)){current=candidate;parts=Math.max(2,parts-1);reduced=true;break;}}if(!reduced){if(parts>=current.size())break;parts=Math.min(current.size(),parts*2);}}
   var catalog=compiler(current);var output=new JsonObject();var recipes=new JsonArray();catalog.catalog().forEach(r->recipes.add(MinimizeStress.recipe(r)));output.add("recipes",recipes);var keys=new LinkedHashSet<String>();catalog.catalog().forEach(r->keys.addAll(r.executionOutputs().keySet()));var producers=new JsonObject();for(String key:keys)producers.add(key,MixedSweep.JSON.toJsonTree(catalog.producers(key).stream().map(GraphRecipe::id).toList()));output.add("producers",producers);output.add("stock",MixedSweep.JSON.toJsonTree(manual.stock()));output.add("external",MixedSweep.JSON.toJsonTree(manual.external()));output.add("request",request);output.add("config",config);output.addProperty("one_minimal",trials<140);output.addProperty("trials",trials);Files.writeString(out.resolve("reduced-catalog.json"),MixedSweep.JSON.toJson(output));
   var added=new JsonArray();current.forEach(r->added.add(MinimizeStress.recipe(r)));Files.writeString(out.resolve("reduced-extra.json"),MixedSweep.JSON.toJson(added));if(!bad(current))throw new AssertionError("Final replay lost failure");System.out.println("FINAL extra="+current.size()+" oneMinimal="+(trials<140));
  }
 }
}
