package org.cgse.core;
import java.util.*;import java.math.*;import java.nio.file.*;import java.lang.reflect.*;import java.lang.management.ManagementFactory;import com.google.gson.Gson;
public final class ReuseComparison {
    static final com.sun.management.ThreadMXBean allocation=(com.sun.management.ThreadMXBean)ManagementFactory.getThreadMXBean();
    static final long thread=Thread.currentThread().getId();
    static PlanningBudget budget(){return new PlanningBudget(0,20_000_000,128L<<20,()->false,System::nanoTime);}
    static List<GraphRecipe<String>> chain(int n){var rs=new ArrayList<GraphRecipe<String>>();for(int i=0;i<n;i++)rs.add(new GraphRecipe<>("r"+i,"r"+i,List.of(new GraphRecipe.Slot<>("k"+i,2)),Map.of("k"+(i+1),3L)));return rs;}
    static final class Stats{long work,bytes,peak;List<Long>times=new ArrayList<>();void add(PlanningBudget b,long start,long allocated){work+=b.nodes();bytes+=allocation.getThreadAllocatedBytes(thread)-allocated;peak=Math.max(peak,b.peakBytes());times.add(System.nanoTime()-start);}Map<String,Object> report(){times.sort(Long::compare);return Map.of("samples",times.size(),"work",work,"allocatedBytes",bytes,"peakBytes",peak,"milliseconds",times.stream().mapToLong(Long::longValue).sum()/1e6,"p50Ms",times.get(times.size()/2)/1e6,"p95Ms",times.get(times.size()*95/100)/1e6);}}
    static Map<String,Object> macro(){var c=new GraphCompiler<>(chain(14));var stats=new Stats();for(int i=0;i<600;i++){var b=budget();var stock=Map.of("k0",Long.MAX_VALUE);long started=System.nanoTime(),allocated=allocation.getThreadAllocatedBytes(thread);try(var m=RecipeCountModel.create(c,"k14",1+i%37,stock,Map.of(),Set.of(),Set.of(),true,b);var execution=new CountExecution<>(m,b);var branch=new IntegerCountBranch<>(m,execution,"k14",1+i%37,stock,Map.of(),Set.of(),false,true,b,started,List.of());var recovery=new CountRecovery<>(branch)){}if(b.reservedBytes()!=0)throw new AssertionError("macro leak");if(i>=100)stats.add(b,started,allocated);}return stats.report();}
    static Map<String,Object> graph(){var c=new GraphCompiler<>(chain(2000));var stats=new Stats();for(int i=0;i<90;i++){var b=budget();long started=System.nanoTime(),allocated=allocation.getThreadAllocatedBytes(thread);var w=c.begin("k2000",Map.of(),Set.of(),b);try{while(!w.step()){}if(w.result().recipes().size()!=2000)throw new AssertionError("graph lost recipes");}finally{if((Object)w instanceof AutoCloseable a)try{a.close();}catch(Exception e){throw new RuntimeException(e);}}if(i>=30)stats.add(b,started,allocated);}return stats.report();}
    static Map<String,Object> demand()throws Exception{var c=new GraphCompiler<>(chain(2000));var g=c.compile("k2000",Map.of(),Set.of(),budget());var stats=new Stats();Method getter=null;try{getter=GraphCompiler.class.getDeclaredMethod("demandProgram",GraphCompiler.Compiled.class,PlanningBudget.class);getter.setAccessible(true);}catch(NoSuchMethodException baseline){}var assembly=GraphSolve.class.getDeclaredField("assembly");assembly.setAccessible(true);
        for(int i=0;i<240;i++){var b=budget();var stock=Map.of("k0",Long.MAX_VALUE);long started=System.nanoTime(),allocated=allocation.getThreadAllocatedBytes(thread);var solve=new GraphSolve<>(g,"k2000",1+i%71,stock,Set.of(),Map.of(),false,true,b,started,CatalystPolicy.STOCK,stock);if(getter!=null){var p=getter.invoke(c,g,b);if(p!=null){var setter=GraphSolve.class.getDeclaredMethod("program",p.getClass());setter.setAccessible(true);setter.invoke(solve,p);}}
            while(assembly.get(solve)==null)if(solve.step())throw new AssertionError("ordinary propagation failed");if(i>=40)stats.add(b,started,allocated);
        }return stats.report();}
    public static void main(String[]args)throws Exception{var report=Map.of("macroPreparationAndOwnerSetup",macro(),"selectedGraphCompilation",graph(),"ordinaryDemandPropagation",demand());Files.writeString(Path.of(args[0],"reuse-comparison.json"),new Gson().toJson(report));System.out.println(report);}
}
