package org.cgse.core;
import java.math.*;import java.util.*;
public class OptimizationOracle {
 static final BigInteger Z=BigInteger.ZERO,O=BigInteger.ONE;
 static PlanningBudget budget(){return new PlanningBudget(0,20000000,256L<<20,()->false,System::nanoTime);}
 static boolean valid(List<ExactLinearProgram.Constraint> rows,BigInteger[] x){for(var r:rows){var s=Z;for(var e:r.terms().entrySet())s=s.add(e.getValue().multiply(x[e.getKey()]));if(s.compareTo(r.upper())>0)return false;}return true;}
 public static void main(String[]args)throws Exception{var rng=new Random(928155);int solved=0,closed=0,reconstructed=0;
 for(int sample=0;sample<2000;sample++){int n=2+rng.nextInt(4);BigInteger[] low=new BigInteger[n],high=new BigInteger[n];Arrays.fill(low,Z);Arrays.fill(high,BigInteger.TWO);var rows=new ArrayList<ExactLinearProgram.Constraint>();var soft=new ArrayList<CountSoftSearch.Soft>();for(int r=0;r<3+rng.nextInt(7);r++){var terms=new TreeMap<Integer,BigInteger>();for(int i=0;i<n;i++){var c=BigInteger.valueOf(rng.nextInt(7)-3);if(c.signum()!=0)terms.put(i,c);}var row=new ExactLinearProgram.Constraint(terms,BigInteger.valueOf(rng.nextInt(7)-2));if(r<2)rows.add(row);else soft.add(new CountSoftSearch.Soft(row,BigInteger.valueOf(1+rng.nextInt(7)).shiftLeft(sample%19==0?90:0)));}BigInteger best=null;for(int code=0;code<(int)Math.pow(3,n);code++){int c=code;BigInteger[] x=new BigInteger[n];for(int i=0;i<n;i++){x[i]=BigInteger.valueOf(c%3);c/=3;}if(!valid(rows,x))continue;var cost=Z;for(var pref:soft)if(!valid(List.of(pref.condition()),x))cost=cost.add(pref.weight());if(best==null||cost.compareTo(best)<0)best=cost;}var b=budget();try(var p=new CountSoftSearch(rows,low,high,soft,b,1000000)){while(!p.step()){}if(best==null){closed++;if(!p.infeasible()||p.counts()!=null)throw new AssertionError("soft unsat "+sample);}else{solved++;if(p.counts()==null||!valid(rows,p.counts())||!p.optimal()||!p.cost().equals(best))throw new AssertionError("soft optimum "+sample+" "+p.cost()+" / "+best+" "+b.diagnostics());}}if(b.reservedBytes()!=0)throw new AssertionError("soft leak");}
 for(int sample=0;sample<2000;sample++){int n=2+rng.nextInt(5);var rows=new ArrayList<ExactLinearProgram.Constraint>();BigInteger[] objective=new BigInteger[n];for(int i=0;i<n;i++){rows.add(new ExactLinearProgram.Constraint(Map.of(i,O),BigInteger.valueOf(6)));objective[i]=BigInteger.valueOf(rng.nextInt(9)-4);}for(int r=0;r<4;r++){var terms=new TreeMap<Integer,BigInteger>();for(int i=0;i<n;i++){var c=BigInteger.valueOf(rng.nextInt(9)-4);if(c.signum()!=0)terms.put(i,c);}rows.add(new ExactLinearProgram.Constraint(terms,BigInteger.valueOf(rng.nextInt(15)-5)));}var b=budget();int[] basis=CountLpProposal.propose(n,rows,objective,b);if(basis!=null){try(var p=new ExactRevisedProgram(n,rows,objective,b);var reference=new ExactLinearProgram(n,rows,objective,b)){if(p.reconstruct(basis)){reconstructed++;while(!p.step()){}while(!reference.step()){}if(p.result()!=reference.result())throw new AssertionError("proposal verdict");if(p.result()==ExactLinearProgram.Result.OPTIMAL){var a=ExactRational.ZERO;var c=ExactRational.ZERO;for(int i=0;i<n;i++){a=a.add(p.point()[i].multiply(ExactRational.of(objective[i])));c=c.add(reference.point()[i].multiply(ExactRational.of(objective[i])));}if(!a.equals(c))throw new AssertionError("proposal objective");}}}}if(b.reservedBytes()!=0)throw new AssertionError("proposal leak");}
 if(solved==0||closed==0||reconstructed==0)throw new AssertionError("unexercised");System.out.println("PASS weighted soft optimization models=2000 exact optima="+solved+" hard UNSAT="+closed+"; numerical basis proposals independently reconstructed="+reconstructed+"/2000");}
}
