package org.cgse.core;
import java.math.*;import java.util.*;
public class ProgramOracle {
 static final BigInteger Z=BigInteger.ZERO,O=BigInteger.ONE;
 static PlanningBudget budget(){return new PlanningBudget(0,20000000,256L<<20,()->false,System::nanoTime);}
 static void word(PlanStep s,List<String> out){if(s instanceof PlanStep.Batch b)out.add(b.recipe()+":"+b.runs());else if(s instanceof PlanStep.Sequence q)for(var c:q.children())word(c,out);else if(s instanceof PlanStep.Repeat r)for(long i=0;i<r.times();i++)word(r.body(),out);}
 static int size(PlanStep s){if(s instanceof PlanStep.Batch)return 1;if(s instanceof PlanStep.Repeat r)return 1+size(r.body());int n=1;for(var c:((PlanStep.Sequence)s).children())n+=size(c);return n;}
 static PlanStep program(Random r,int d){if(d==0)return new PlanStep.Batch("r"+r.nextInt(4),1+r.nextInt(5));if(r.nextInt(3)==0)return new PlanStep.Repeat(program(r,d-1),r.nextInt(4));var children=new ArrayList<PlanStep>();for(int i=0;i<r.nextInt(6);i++)children.add(r.nextBoolean()&&!children.isEmpty()?children.get(r.nextInt(children.size())):program(r,d-1));return new PlanStep.Sequence(children);}
 public static void main(String[]args){var rng=new Random(983919);int reduced=0,warm=0;
 for(int length:new int[]{2,32,1024,4096}){var children=new ArrayList<PlanStep>();for(int i=0;i<length;i++)children.add(new PlanStep.Batch("unique"+i,1));PlanStep flat=new PlanStep.Sequence(children);for(PlanStep p:List.of(flat,new PlanStep.Repeat(flat,Long.MAX_VALUE))){var b=budget();if(PlanEGraph.optimize(p,b)!=p||b.nodes()!=length||b.reservedBytes()!=0)throw new AssertionError("irreducible atomic word "+length);}}
 var duplicate=new PlanStep.Sequence(List.of(new PlanStep.Batch("a",1),new PlanStep.Batch("b",1),new PlanStep.Batch("a",1),new PlanStep.Batch("b",1)));if(size(PlanEGraph.optimize(duplicate,budget()))>=size(duplicate))throw new AssertionError("missed repeated word");
 for(int test=0;test<2000;test++){var p=program(rng,3);var b=budget();PlanStep q=PlanEGraph.optimize(p,b);var a=new ArrayList<String>();var c=new ArrayList<String>();word(p,a);word(q,c);if(!a.equals(c))throw new AssertionError("changed batch word "+test);if(size(q)>size(p))throw new AssertionError("larger program");if(size(q)<size(p))reduced++;if(b.reservedBytes()!=0)throw new AssertionError("egraph leak");}
 var atom=new PlanStep.Sequence(List.of(new PlanStep.Batch("a",1),new PlanStep.Batch("b",1)));var huge=new PlanStep.Repeat(new PlanStep.Repeat(atom,1000000000),1000000000);var b=budget();var compressed=PlanEGraph.optimize(huge,b);if(!PlanCountComputation.of(huge).equals(PlanCountComputation.of(compressed)))throw new AssertionError("huge program");
 for(int test=0;test<1000;test++){int n=2+rng.nextInt(5);BigInteger[] objective=new BigInteger[n];var rows=new ArrayList<ExactLinearProgram.Constraint>();for(int i=0;i<n;i++){objective[i]=BigInteger.valueOf(rng.nextInt(11)-5);rows.add(new ExactLinearProgram.Constraint(Map.of(i,O),BigInteger.valueOf(5)));}for(int r=0;r<3;r++){var terms=new TreeMap<Integer,BigInteger>();for(int i=0;i<n;i++){var c=BigInteger.valueOf(rng.nextInt(9)-4);if(c.signum()!=0)terms.put(i,c);}rows.add(new ExactLinearProgram.Constraint(terms,BigInteger.valueOf(rng.nextInt(15))));}b=budget();try(var parent=new ExactRevisedProgram(n,rows,objective,b)){while(!parent.step()){}if(parent.result()!=ExactLinearProgram.Result.OPTIMAL)continue;try(var basis=parent.snapshot()){if(basis==null)continue;for(int branch=0;branch<3;branch++){var child=new ArrayList<>(rows);int id=rng.nextInt(n);child.add(new ExactLinearProgram.Constraint(Map.of(id,branch==1?O.negate():O),BigInteger.valueOf(branch==1?-rng.nextInt(7):rng.nextInt(5))));try(var hot=new ExactLinearProgram(n,child,objective,b,basis,true);var cold=new ExactLinearProgram(n,child,objective,b)){while(!hot.step()){}while(!cold.step()){}if(hot.result()!=cold.result())throw new AssertionError("warm status "+test+" "+hot.result()+"/"+cold.result()+" "+b.diagnostics());if(hot.result()==ExactLinearProgram.Result.OPTIMAL){var h=ExactRational.ZERO;var c=ExactRational.ZERO;for(int i=0;i<n;i++){h=h.add(hot.point()[i].multiply(ExactRational.of(objective[i])));c=c.add(cold.point()[i].multiply(ExactRational.of(objective[i])));}if(!h.equals(c))throw new AssertionError("warm cost");}if(hot.hot())warm++;try(var transfer=hot.takeBasis()){} }}}}if(b.reservedBytes()!=0)throw new AssertionError("warm leak "+b.reservedBytes());}
 if(reduced==0||warm==0)throw new AssertionError("not exercised");System.out.println("PASS egraph batch-word preservation programs=2000 reduced="+reduced+"; exact warm sparse LP vs dense cold branches="+warm);
 }
}
