package org.cgse.core;
import java.math.*;import java.util.*;
public final class DomainOracle {
 static final BigInteger Z=BigInteger.ZERO,O=BigInteger.ONE;
 static boolean valid(List<ExactLinearProgram.Constraint> rows,BigInteger[] x){for(var r:rows){var s=Z;for(var e:r.terms().entrySet())s=s.add(e.getValue().multiply(x[e.getKey()]));if(s.compareTo(r.upper())>0)return false;}return true;}
 public static void main(String[] args){var rng=new Random(2714);long checked=0;int sat=0,unsat=0,clauses=0;
 for(int sample=0;sample<3000;sample++){int n=2+rng.nextInt(5),total=1;int[] size=new int[n];BigInteger[] low=new BigInteger[n],high=new BigInteger[n],plant=new BigInteger[n];for(int i=0;i<n;i++){low[i]=sample%13==0?O.shiftLeft(90):Z;size[i]=1+rng.nextInt(5);total*=size[i];high[i]=low[i].add(BigInteger.valueOf(size[i]-1));plant[i]=low[i].add(BigInteger.valueOf(rng.nextInt(size[i])));}
 var rows=new ArrayList<ExactLinearProgram.Constraint>();for(int r=0;r<3+rng.nextInt(7);r++){var terms=new LinkedHashMap<Integer,BigInteger>();var rhs=BigInteger.valueOf(rng.nextInt(3)-1);for(int i=0;i<n;i++){var c=BigInteger.valueOf(rng.nextInt(9)-4);if(sample%17==0)c=c.multiply(O.shiftLeft(130));if(c.signum()!=0)terms.put(i,c);rhs=rhs.add(c.multiply(plant[i]));}rows.add(new ExactLinearProgram.Constraint(terms,rhs));}
 var solutions=new ArrayList<BigInteger[]>();for(int code=0;code<total;code++){int v=code;var x=low.clone();for(int i=0;i<n;i++){x[i]=x[i].add(BigInteger.valueOf(v%size[i]));v/=size[i];}checked++;if(valid(rows,x))solutions.add(x);}
 var budget=new PlanningBudget(0,20000000,256L<<20,()->false,System::nanoTime);try(var p=new CountDomainSearch(rows,low,high,budget,2000000)){while(!p.step()){}var x=p.counts();if(!solutions.isEmpty()){sat++;if(x==null||p.infeasible()||!valid(rows,x))throw new AssertionError("missed solution "+sample);for(int i=0;i<n;i++)if(x[i].compareTo(low[i])<0||x[i].compareTo(high[i])>0)throw new AssertionError("domain");}else{unsat++;if(x!=null||!p.infeasible())throw new AssertionError("missed unsat "+sample);}for(var c:p.learnedConflicts()){clauses++;for(var solution:solutions)if(valid(c.assumptions(),solution))throw new AssertionError("bad mapped clause "+sample);}}
 if(budget.reservedBytes()!=0)throw new AssertionError("leak");}
 var rows=List.of(new ExactLinearProgram.Constraint(Map.of(0,O.negate()),BigInteger.TWO.negate()));var budget=new PlanningBudget(0,20000000,256L<<20,()->false,System::nanoTime);try(var p=new CountDomainSearch(rows,new BigInteger[]{O},new BigInteger[]{null},budget,2000000)){while(!p.step()){}if(p.infeasible()||!p.learnedConflicts().isEmpty())throw new AssertionError("trial escaped scope");}
 for(int limit=1;limit<512;limit++){int[] counter={0};int stop=limit;var b=new PlanningBudget(0,20000000,256L<<20,()->++counter[0]>=stop,System::nanoTime);try(var p=new CountDomainSearch(rows,new BigInteger[]{Z},new BigInteger[]{BigInteger.valueOf(8)},b,2000000)){while(!p.step()){}}catch(java.util.concurrent.CancellationException expected){}if(b.reservedBytes()!=0)throw new AssertionError("cancel leak "+limit);}
 System.out.println("PASS order encoding models=3000 assignments="+checked+" SAT="+sat+" UNSAT="+unsat+" exact_mapped_clauses="+clauses+"; offset/large coefficients, trial isolation, 511 cancellation boundaries");}
}
