package org.cgse.core;
import java.math.*; import java.util.*;
public class AffineOracle {
 static final BigInteger Z=BigInteger.ZERO,O=BigInteger.ONE;
 static PlanningBudget budget(){return new PlanningBudget(0,20_000_000,256L<<20,()->false,System::nanoTime);}
 static void equation(List<ExactLinearProgram.Constraint>rows,Map<Integer,BigInteger>a,BigInteger b){rows.add(new ExactLinearProgram.Constraint(a,b));var m=new TreeMap<Integer,BigInteger>();a.forEach((i,v)->m.put(i,v.negate()));rows.add(new ExactLinearProgram.Constraint(m,b.negate()));}
 static boolean valid(List<ExactLinearProgram.Constraint>rows,BigInteger[]lo,BigInteger[]hi,BigInteger[]x){for(int i=0;i<x.length;i++)if(x[i].compareTo(lo[i])<0||x[i].compareTo(hi[i])>0)return false;for(var r:rows){var v=Z;for(var e:r.terms().entrySet())v=v.add(e.getValue().multiply(x[e.getKey()]));if(v.compareTo(r.upper())>0)return false;}return true;}
 static boolean enumerate(List<ExactLinearProgram.Constraint>rows,BigInteger[]lo,BigInteger[]hi){var x=lo.clone();while(true){if(valid(rows,lo,hi,x))return true;int i=0;while(i<x.length&&x[i].equals(hi[i])){x[i]=lo[i];i++;}if(i==x.length)return false;x[i]=x[i].add(O);}}
 public static void main(String[]args){var rng=new Random(2809621);int found=0,feasible=0;
  for(int t=0;t<2400;t++){int n=4+rng.nextInt(3);var lo=new BigInteger[n];var hi=new BigInteger[n];var target=new BigInteger[n];for(int i=0;i<n;i++){lo[i]=BigInteger.valueOf(rng.nextInt(3)-1);hi[i]=lo[i].add(BigInteger.valueOf(3));target[i]=lo[i].add(BigInteger.valueOf(rng.nextInt(4)));}var rows=new ArrayList<ExactLinearProgram.Constraint>();for(int i=0;i<n-1;i++){var a=new TreeMap<Integer,BigInteger>();a.put(i,BigInteger.valueOf(2+rng.nextInt(9)));a.put(n-1,BigInteger.valueOf(rng.nextInt(25)-12));if(a.get(n-1).signum()==0)a.remove(n-1);var b=Z;for(var e:a.entrySet())b=b.add(e.getValue().multiply(target[e.getKey()]));if(t%3==0&&i==0)b=b.add(O);equation(rows,a,b);}if(t%4==0)rows.add(new ExactLinearProgram.Constraint(Map.of(0,O,1,O),BigInteger.valueOf(rng.nextInt(8)-2)));Collections.shuffle(rows,rng);boolean truth=enumerate(rows,lo,hi);if(truth)feasible++;var b=budget();try(var p=new CountAffineLattice(rows,lo,hi,b)){int ticks=0;while(!p.step())if(++ticks>10000)throw new AssertionError("no progress");if(p.counts()!=null){found++;if(!valid(rows,lo,hi,p.counts()))throw new AssertionError("invalid witness "+t);}if(truth!=(p.counts()!=null))throw new AssertionError("rank n-1 completeness "+t+" "+b.diagnostics());}if(b.reservedBytes()!=0)throw new AssertionError("leak");}
  int wideFound=0;for(int t=0;t<400;t++){int n=4+rng.nextInt(13);var lo=new BigInteger[n];var hi=new BigInteger[n];var target=new BigInteger[n];Arrays.fill(lo,Z);Arrays.fill(hi,O.shiftLeft(t%7==0?90:22));for(int i=0;i<n;i++)target[i]=hi[i].multiply(BigInteger.valueOf(5+rng.nextInt(7))).divide(BigInteger.valueOf(16));var rows=new ArrayList<ExactLinearProgram.Constraint>();for(int r=0;r<2+t%3;r++){var a=new TreeMap<Integer,BigInteger>();var b=Z;for(int i=0;i<n;i++){var v=BigInteger.valueOf(rng.nextInt(4001)-2000);if(v.signum()!=0)a.put(i,v);b=b.add(v.multiply(target[i]));}equation(rows,a,b);}var b=budget();try(var p=new CountAffineLattice(rows,lo,hi,b)){while(!p.step()){}if(p.counts()!=null){wideFound++;if(!valid(rows,lo,hi,p.counts()))throw new AssertionError("invalid large witness");}}if(b.reservedBytes()!=0)throw new AssertionError("wide leak");}
  var rows=new ArrayList<ExactLinearProgram.Constraint>();equation(rows,Map.of(0,BigInteger.valueOf(495),1,BigInteger.valueOf(866),2,BigInteger.valueOf(609),3,BigInteger.valueOf(558)),BigInteger.valueOf(967206347));equation(rows,Map.of(0,BigInteger.valueOf(782),1,BigInteger.valueOf(321),2,BigInteger.valueOf(36),3,BigInteger.valueOf(773)),BigInteger.valueOf(545260065));equation(rows,Map.of(0,BigInteger.valueOf(317),1,BigInteger.valueOf(195),2,BigInteger.valueOf(726),3,BigInteger.valueOf(127)),BigInteger.valueOf(425546456));var lo=new BigInteger[]{Z,Z,Z,Z};var hi=new BigInteger[]{BigInteger.valueOf(697263),BigInteger.valueOf(1000014),BigInteger.valueOf(586152),BigInteger.valueOf(705381)};
  for(int stop=1;stop<=1500;stop++){int[]checks={0};int at=stop;var b=new PlanningBudget(0,20000000,256L<<20,()->++checks[0]>=at,System::nanoTime);try(var p=new CountDiophantine(rows,lo,hi,b)){while(!p.step()){}}catch(java.util.concurrent.CancellationException ok){}if(b.reservedBytes()!=0)throw new AssertionError("cancel leak "+stop);}
  for(long mem:new long[]{1,4096,16384,65536,131072}){var b=new PlanningBudget(0,20000000,mem,()->false,System::nanoTime);try(var p=new CountDiophantine(rows,lo,hi,b)){while(!p.step()){}if(p.counts()!=null&&!valid(rows,lo,hi,p.counts()))throw new AssertionError("memory invalid");}if(b.reservedBytes()!=0)throw new AssertionError("memory leak");}
  System.out.println("PASS affine 2400 enumerated rank n-1 models; feasible="+feasible+" found="+found+"; 400 wide/90-bit models witnesses="+wideFound+"; 1500 cancellation points and 5 memory limits");
 }
}
