package org.cgse.core;
import java.math.*;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.*;import java.util.function.*;
public class LifecycleOracle {
 static final BigInteger Z=BigInteger.ZERO,O=BigInteger.ONE;
 static PlanningBudget budget(){return new PlanningBudget(0,20000000,256L<<20,()->false,System::nanoTime);}
 static final class Work implements PlanningScheduler.Work<List<Integer>> {
   final int n;final AtomicIntegerArray calls;final boolean fail,stall;final CountDownLatch started=new CountDownLatch(1);final AtomicBoolean release=new AtomicBoolean();final AtomicInteger closed=new AtomicInteger();CompletableFuture<List<Integer>> waiting;List<Integer> result;
   Work(int n,boolean fail,boolean stall){this.n=n;this.fail=fail;this.stall=stall;calls=new AtomicIntegerArray(n);}
   public boolean advance(PlanningScheduler.Slice s){if(waiting==null){List<Supplier<Integer>> tasks=new ArrayList<>();for(int i=0;i<n;i++){int id=i;tasks.add(()->{if(calls.incrementAndGet(id)!=1)throw new AssertionError("double work");started.countDown();while(stall&&!release.get()){s.budget().check();Thread.onSpinWait();}for(int k=0;k<100+id*17;k++)s.budget().check();if(fail&&id==n/2)throw new IllegalStateException("injected");return id;});}waiting=s.forkStealing(PlanningBudget.Phase.SOLVE,tasks);return false;}result=waiting.join();return true;}
   public CompletableFuture<?> waitingFor(){return waiting;}public List<Integer> result(){return result;}public void close(){closed.incrementAndGet();release.set(true);}
 }
 public static void main(String[]args)throws Exception {
 for(int workers:new int[]{1,4,8,16})for(int mode=0;mode<4;mode++){var b=budget();var work=new Work(2*workers,mode==1,mode>=2);try(var scheduler=new PlanningScheduler(workers,8,128,1000000)){var f=scheduler.submit(work,b);if(mode>=2){if(!work.started.await(3,TimeUnit.SECONDS))throw new AssertionError("not started");if(mode==2)f.cancel(false);else scheduler.close();work.release.set(true);}try{var value=f.get(5,TimeUnit.SECONDS);if(mode!=0)throw new AssertionError("failure lost");for(int i=0;i<work.n;i++)if(value.get(i)!=i||work.calls.get(i)!=1)throw new AssertionError("lost/reordered task");}catch(ExecutionException|CancellationException e){if(mode==0)throw e;}long deadline=System.nanoTime()+TimeUnit.SECONDS.toNanos(3);while(work.closed.get()==0&&System.nanoTime()<deadline)Thread.onSpinWait();if(work.closed.get()!=1||scheduler.peakActive()>workers)throw new AssertionError("dispose/worker limit");}if(b.reservedBytes()!=0)throw new AssertionError("scheduler budget leak");}
 var recipes=List.of(new GraphRecipe<String>("a","a",List.of(new GraphRecipe.Slot<>("A",1)),Map.of("Q",1L)),new GraphRecipe<String>("b","b",List.of(new GraphRecipe.Slot<>("A",1)),Map.of("Q",2L)));var compiler=new GraphCompiler<>(recipes);var session=new CountSessions();var budget=budget();
 try(var first=RecipeCountModel.create(compiler,"Q",1,Map.of("A",1L),Map.of(),Set.of(),Set.of(),false,budget)){var conflict=new CountConflict(List.of(new ExactLinearProgram.Constraint(Map.of(0,O.negate()),BigInteger.TWO.negate())));session.remember(first,List.of(conflict),budget);if(session.reuse(first,budget).isEmpty())throw new AssertionError("session not retained");}
 for(long stock:new long[]{0,1,2,10})try(var next=RecipeCountModel.create(compiler,"Q",1,Map.of("A",stock),Map.of(),Set.of(),Set.of(),false,budget)){boolean reused=!session.reuse(next,budget).isEmpty();if(reused!=(stock<=1))throw new AssertionError("stale assumptions reused "+stock);}
 if(budget.reservedBytes()!=0)throw new AssertionError("session leak");
 var rows=List.of(new ExactLinearProgram.Constraint(Map.of(0,O,1,O),BigInteger.valueOf(12)),new ExactLinearProgram.Constraint(Map.of(0,O),BigInteger.valueOf(8)),new ExactLinearProgram.Constraint(Map.of(1,O),BigInteger.valueOf(8)));BigInteger[] obj={O,O};int cancelled=0;
 for(int cutoff=1;cutoff<384;cutoff++){var count=new AtomicInteger();var armed=new AtomicBoolean();int limit=cutoff;var b=new PlanningBudget(0,20000000,256L<<20,()->armed.get()&&count.incrementAndGet()>=limit,System::nanoTime);try(var lp=new ExactRevisedProgram(2,rows,obj,b)){while(!lp.step()){}try(var basis=lp.snapshot()){armed.set(true);var next=new ArrayList<>(rows);next.add(new ExactLinearProgram.Constraint(Map.of(0,O),BigInteger.TWO));try(var hot=new ExactLinearProgram(2,next,obj,b,basis,true)){while(!hot.step()){}try(var held=hot.takeBasis()){} }catch(PlanningBudget.Exhausted|CancellationException stopped){cancelled++;}}}if(b.reservedBytes()!=0)throw new AssertionError("sparse warm cancellation leaked "+cutoff+" "+b.reservedBytes());}
 System.out.println("PASS work claiming / failure / cancellation / shutdown at 1,4,8,16 workers; stock-scoped sessions; sparse warm cancellation boundaries="+cancelled);
 }
}
