package org.cgse.core;
import java.math.*;import java.util.*;
public class CoreLearningOracle {
 static final BigInteger Z=BigInteger.ZERO,O=BigInteger.ONE;
 static PlanningBudget b(){return new PlanningBudget(0,20000000,256L<<20,()->false,System::nanoTime);}
 static BitSet bits(int...xs){var b=new BitSet();for(int x:xs)b.set(x);return b;}
 static boolean hits(List<BitSet> cores,BigInteger[]x){for(var c:cores){boolean hit=false;for(int i=c.nextSetBit(0);i>=0;i=c.nextSetBit(i+1))if(x[i].equals(O))hit=true;if(!hit)return false;}return true;}
 static BigInteger cost(BigInteger[]x,BigInteger[]w){var c=Z;for(int i=0;i<w.length;i++){if(!x[i].equals(Z)&&!x[i].equals(O))throw new AssertionError("not binary");c=c.add(x[i].multiply(w[i]));}return c;}
 static void checkHit(CountHittingSet p,List<BitSet>cores,BigInteger[]w,BigInteger best){
  if(best!=null&&p.lowerBound().compareTo(best)>0)throw new AssertionError("invalid hitting-set lower "+p.lowerBound()+" "+best);
  if(p.infeasible()&&best!=null)throw new AssertionError("false hitting-set infeasible");
  if(p.counts()!=null&&(!hits(cores,p.counts())||!cost(p.counts(),w).equals(p.cost())||best==null||p.cost().compareTo(best)<0))throw new AssertionError("bad hitting-set incumbent");
  if(p.optimal()&&(p.counts()==null||!best.equals(p.cost())))throw new AssertionError("false optimum");
 }
 public static void main(String[]args){var rng=new Random(928614);long assignments=0;int closed=0;
  for(int t=0;t<3000;t++){int n=1+rng.nextInt(11);var w=new BigInteger[n];for(int i=0;i<n;i++)w[i]=BigInteger.valueOf(1+rng.nextInt(29)).shiftLeft(t%11==0?150:0);var cores=new ArrayList<BitSet>();for(int j=0;j<1+rng.nextInt(20);j++){var c=new BitSet();for(int i=0;i<n;i++)if(rng.nextInt(3)==0)c.set(i);if(t%7!=0&&c.isEmpty())c.set(rng.nextInt(n));cores.add(c);}BigInteger best=null;for(int v=0;v<1<<n;v++){var x=new BigInteger[n];for(int i=0;i<n;i++)x[i]=(v&1<<i)==0?Z:O;assignments++;if(hits(cores,x)){var k=cost(x,w);if(best==null||k.compareTo(best)<0)best=k;}}
   var b=b();try(var p=new CountHittingSet(cores,w,b,500000)){int ticks=0;while(!p.step()){checkHit(p,cores,w,best);if(++ticks>200000)throw new AssertionError("not bounded");}checkHit(p,cores,w,best);if(best==null?!p.infeasible():!p.optimal())throw new AssertionError("unfinished tiny hitting set "+t);closed++;}if(b.reservedBytes()!=0)throw new AssertionError("hitting leak");
   var q=b();try(var p=new CountHittingSet(cores,w,q,256+rng.nextInt(1200))){while(!p.step()){}checkHit(p,cores,w,best);}if(q.reservedBytes()!=0)throw new AssertionError("bounded hit leak");
  }
  var w=new BigInteger[64];Arrays.fill(w,O.shiftLeft(140));var cores=List.of(bits(63),bits(0,62),bits(1,2),bits(0,62,63));var b=b();try(var p=new CountHittingSet(cores,w,b,65536)){while(!p.step()){}checkHit(p,cores,w,w[0].multiply(BigInteger.valueOf(3)));if(!p.optimal()||p.counts()[63].signum()==0)throw new AssertionError("64th bit");}if(b.reservedBytes()!=0)throw new AssertionError("64 bit leak");
  int shrunk=0;for(int t=0;t<300;t++){int n=2+rng.nextInt(5);var low=new BigInteger[n];var high=new BigInteger[n];Arrays.fill(low,Z);Arrays.fill(high,BigInteger.valueOf(2));var hard=List.of(new ExactLinearProgram.Constraint(Map.of(0,O,1,O),O));var soft=new ArrayList<CountSoftSearch.Soft>();for(int i=0;i<12;i++){int id=i<2?i:rng.nextInt(n);var r=new ExactLinearProgram.Constraint(Map.of(id,i<2?O.negate():O),i<2?O.negate():BigInteger.valueOf(2+rng.nextInt(5)));soft.add(new CountSoftSearch.Soft(r,O));}Collections.shuffle(soft,rng);var all=new ArrayList<>(hard);for(var s:soft)all.add(s.condition());var bud=b();var j=new CountProof.Journal(32L<<20);bud.proofJournal(j);try(var p=new CountLcg(all,low,high,bud,100000,true)){while(!p.step()){}if(!p.infeasible()||CountProof.verify(p.certificate(),200000)!=CountProof.Verdict.VERIFIED)throw new AssertionError("initial core");var ids=new BitSet();ids.set(0,soft.size());try(var m=new CountCoreMinimize(hard,low,high,soft,ids,p.certificate(),bud,100000)){while(!m.step()){}if(m.core().cardinality()!=2)throw new AssertionError("did not remove irrelevant core "+m.core()+" "+bud.diagnostics());shrunk++;if(CountProof.verify(m.certificate(),200000)!=CountProof.Verdict.VERIFIED)throw new AssertionError("shrunk proof");var only=new ArrayList<>(hard);for(int k=m.core().nextSetBit(0);k>=0;k=m.core().nextSetBit(k+1))only.add(soft.get(k).condition());if(MechanismsOracle.values(n,3).stream().anyMatch(x->OptimizationOracle.valid(only,x)))throw new AssertionError("false core");var bad=new ArrayList<>(m.certificate().axioms());bad.remove(hard.size());var tampered=new CountProof.Certificate("tampered",n,bad,m.certificate().forbidden(),List.of(),true);if(CountProof.verify(tampered,200000)==CountProof.Verdict.VERIFIED)throw new AssertionError("tamper accepted");}}MechanismsOracle.proofs(j);if(bud.reservedBytes()!=0)throw new AssertionError("minimize leak");}
  for(int limit=1;limit<1200;limit++){int[]checks={0};int stop=limit;var bud=new PlanningBudget(0,20000000,256L<<20,()->++checks[0]>=stop,System::nanoTime);try(var p=new CountHittingSet(cores,w,bud,100000)){while(!p.step()){}}catch(java.util.concurrent.CancellationException ok){}if(bud.reservedBytes()!=0)throw new AssertionError("cancel hitting leak "+limit);}
  for(int limit=1;limit<1200;limit++){int[]checks={0};int stop=limit;var bud=new PlanningBudget(0,20000000,256L<<20,()->++checks[0]>=stop,System::nanoTime);var hard=List.of(new ExactLinearProgram.Constraint(Map.of(0,O,1,O),O));var soft=new ArrayList<CountSoftSearch.Soft>();for(int j=0;j<10;j++)soft.add(new CountSoftSearch.Soft(new ExactLinearProgram.Constraint(Map.of(j<2?j:0,j<2?O.negate():O),j<2?O.negate():BigInteger.TWO),O));try(var p=new CountCoreSoft(hard,new BigInteger[]{Z,Z},new BigInteger[]{O,O},soft,bud,100000)){while(!p.step()){}}catch(java.util.concurrent.CancellationException ok){}if(bud.reservedBytes()!=0)throw new AssertionError("cancel soft leak "+limit);}
  for(long mem:new long[]{1,4096,16384,65536,131072}){var bud=new PlanningBudget(0,20000000,mem,()->false,System::nanoTime);try(var p=new CountHittingSet(cores,w,bud,100000)){while(!p.step()){}checkHit(p,cores,w,w[0].multiply(BigInteger.valueOf(3)));}if(bud.reservedBytes()!=0)throw new AssertionError("memory boundary");}
  System.out.println("PASS hitting-set 3000 models closed="+closed+" assignments="+assignments+"; partial bounds, 150-bit weights, selector 63; shrunk cores="+shrunk+"; proof tamper, 2398 cancellation points and memory limits");
 }
}
