package org.cgse.core;
import java.math.*;import java.util.*;
public class InductionOracle {
 static final BigInteger Z=BigInteger.ZERO,O=BigInteger.ONE;
 static PlanningBudget budget(){return new PlanningBudget(0,20000000,256L<<20,()->false,System::nanoTime);}
 static boolean valid(List<ExactLinearProgram.Constraint> rows,BigInteger[] x){for(var r:rows){BigInteger s=Z;for(var e:r.terms().entrySet())s=s.add(e.getValue().multiply(x[e.getKey()]));if(s.compareTo(r.upper())>0)return false;}return true;}
 static boolean covered(int[] state,int[] target){for(int i=0;i<state.length;i++)if(state[i]<target[i])return false;return true;}
 static boolean bfs(int[][] in,int[][] out,int[] stock,int[] goal){Set<List<Integer>> seen=new HashSet<>();Deque<int[]> q=new ArrayDeque<>();q.add(stock);while(!q.isEmpty()){int[] s=q.removeFirst();if(covered(s,goal))return true;if(!seen.add(Arrays.stream(s).boxed().toList()))continue;for(int r=0;r<in.length;r++)if(covered(s,in[r])){int[] t=s.clone();for(int i=0;i<t.length;i++)t[i]+=out[r][i]-in[r][i];q.add(t);}}return false;}
 public static void main(String[]args)throws Exception{
 Random rng=new Random(928918);int cuts=0,pump=0,strong=0,pdrsat=0,pdrunsat=0,unknown=0;
 for(int test=0;test<500;test++){int n=2+rng.nextInt(4),t=1+rng.nextInt(7);int[][] in=new int[t][n],out=new int[t][n];var recipes=new ArrayList<GraphRecipe<String>>();var names=new ArrayList<String>();for(int i=0;i<n;i++)names.add("k"+i);for(int r=0;r<t;r++){int take=1+rng.nextInt(3);for(int j=0;j<take;j++)in[r][rng.nextInt(n)]++;for(int j=0;j<take-(rng.nextInt(5)==0?1:0);j++)out[r][rng.nextInt(n)]++;var slots=new ArrayList<GraphRecipe.Slot<String>>();var outputs=new LinkedHashMap<String,Long>();for(int i=0;i<n;i++){if(in[r][i]>0)slots.add(new GraphRecipe.Slot<>(names.get(i),in[r][i]));if(out[r][i]>0)outputs.put(names.get(i),(long)out[r][i]);}if(outputs.isEmpty()){out[r][0]=1;outputs.put(names.get(0),1L);}recipes.add(new GraphRecipe<>("r"+r,"r"+r,slots,outputs));}int[] stock=new int[n],goal=new int[n];for(int j=0;j<1+rng.nextInt(6);j++)stock[rng.nextInt(n)]++;for(int j=0;j<1+rng.nextInt(6);j++)goal[rng.nextInt(n)]++;boolean possible=bfs(in,out,stock,goal);var b=budget();var journal=new CountProof.Journal(32L<<20);b.proofJournal(journal);try(var p=new CountInduction<>(recipes,names,Arrays.stream(stock).mapToObj(BigInteger::valueOf).toList(),Arrays.stream(goal).mapToObj(BigInteger::valueOf).toList(),b,1000000)){while(!p.step()){}if(p.result()==BackwardCoverability.Result.UNKNOWN)unknown++;else if(p.result()==BackwardCoverability.Result.CLOSED){pdrunsat++;if(CountInduction.verify(p.proof(),20000000,u->{})!=CountProof.Verdict.VERIFIED)throw new AssertionError("induction proof");if(possible)throw new AssertionError("false PDR closed "+test);}else{pdrsat++;if(!possible)throw new AssertionError("false PDR witness "+test);var map=new HashMap<String,GraphRecipe<String>>();for(var r:recipes)map.put(r.id(),r);try(var summary=new SummaryComputation<>(p.witness(),map,b)){while(!summary.step()){}var s=summary.result();for(int i=0;i<n;i++)if(s.required(names.get(i)).compareTo(BigInteger.valueOf(stock[i]))>0||BigInteger.valueOf(stock[i]).add(s.delta(names.get(i))).compareTo(BigInteger.valueOf(goal[i]))<0)throw new AssertionError("PDR bad program");}}}for(var p:journal.executions())if(ExecutionProof.verify(p,20000000)!=CountProof.Verdict.VERIFIED)throw new AssertionError("PDR proof "+test);if(b.reservedBytes()!=0)throw new AssertionError("PDR leak");}
 if(pdrsat==0||pdrunsat==0)throw new AssertionError("untested path");System.out.println("PASS k-induction vs complete BFS networks=500 SAT="+pdrsat+" UNSAT="+pdrunsat+" UNKNOWN="+unknown);
 }
}
