package org.cgse.core;
import java.math.*;import java.util.*;
public final class FlowCostOracle {
 static final BigInteger Z=BigInteger.ZERO,O=BigInteger.ONE;
 static boolean valid(List<ExactLinearProgram.Constraint> rows,BigInteger[] x){for(var r:rows){var s=Z;for(var e:r.terms().entrySet())s=s.add(e.getValue().multiply(x[e.getKey()]));if(s.compareTo(r.upper())>0)return false;}return true;}
 static PlanningBudget budget(){return new PlanningBudget(0,20000000,256L<<20,()->false,System::nanoTime);}
 public static void main(String[]args){var rng=new Random(614842);long checked=0;int sat=0,unsat=0;
 for(int test=0;test<5000;test++){int n=2+rng.nextInt(6),m=1+rng.nextInt(6),total=1;var lo=new BigInteger[n];var hi=new BigInteger[n];var plant=new BigInteger[n];int[]size=new int[n],sign=new int[m];var rows=new ArrayList<ExactLinearProgram.Constraint>();var terms=new ArrayList<Map<Integer,BigInteger>>();for(int r=0;r<m;r++){terms.add(new LinkedHashMap<>());sign[r]=rng.nextBoolean()?1:-1;}
  for(int i=0;i<n;i++){lo[i]=test%29==0?O.shiftLeft(100):BigInteger.valueOf(rng.nextInt(3));size[i]=1+rng.nextInt(4);hi[i]=lo[i].add(BigInteger.valueOf(size[i]-1));plant[i]=lo[i].add(BigInteger.valueOf(rng.nextInt(size[i])));total*=size[i];int a=rng.nextInt(m+1),b=rng.nextInt(m);if(b>=a)b++;if(a<m)terms.get(a).put(i,BigInteger.valueOf(sign[a]));if(b<m)terms.get(b).put(i,BigInteger.valueOf(-sign[b]));}
  for(int r=0;r<m;r++){BigInteger rhs=BigInteger.valueOf(rng.nextInt(5)-2);for(var e:terms.get(r).entrySet())rhs=rhs.add(e.getValue().multiply(plant[e.getKey()]));rows.add(new ExactLinearProgram.Constraint(terms.get(r),rhs));}
  if(test%3!=0)for(var row:List.copyOf(rows)){var opposite=new LinkedHashMap<Integer,BigInteger>();row.terms().forEach((id,value)->opposite.put(id,value.negate()));rows.add(new ExactLinearProgram.Constraint(opposite,row.upper().negate()));}
  BigInteger[] costs=new BigInteger[n];for(int i=0;i<n;i++)costs[i]=BigInteger.valueOf(rng.nextInt(10)); BigInteger best=null; boolean feasible=false;for(int code=0;code<total;code++){int c=code;var x=lo.clone();for(int i=0;i<n;i++){x[i]=x[i].add(BigInteger.valueOf(c%size[i]));c/=size[i];}checked++;boolean ok=valid(rows,x);feasible|=ok;if(ok){var cost=Z;for(int i=0;i<n;i++)cost=cost.add(costs[i].multiply(x[i]));if(best==null||cost.compareTo(best)<0)best=cost;}}
  var b=budget();var journal=new CountProof.Journal(16L<<20);b.proofJournal(journal);try(var solver=new CountNetwork(rows,lo,hi,b).minimize(costs)){while(!solver.step()){}var x=solver.counts();if(feasible){sat++;var cost=Z;if(x!=null)for(int i=0;i<n;i++)cost=cost.add(costs[i].multiply(x[i]));if(!cost.equals(best))throw new AssertionError("nonminimal flow "+test+" "+cost+" vs "+best+" "+b.diagnostics());if(x==null||solver.infeasible()||!valid(rows,x))throw new AssertionError("SAT "+test+" "+b.diagnostics()+" "+rows);for(int i=0;i<n;i++)if(x[i].compareTo(lo[i])<0||x[i].compareTo(hi[i])>0)throw new AssertionError("domain");}else{unsat++;if(x!=null)throw new AssertionError("false SAT "+test);if(!solver.infeasible()&&!b.diagnostics().contains("empty_domain"))throw new AssertionError("UNSAT "+test+" "+b.diagnostics()+" "+rows);}}
  for(var proof:journal.entries())if(CountProof.verify(proof,2000000)!=CountProof.Verdict.VERIFIED)throw new AssertionError("mincut certificate");if(b.reservedBytes()!=0)throw new AssertionError("leak");
 }
 var huge=O.shiftLeft(130);var rows=List.of(new ExactLinearProgram.Constraint(Map.of(0,O,1,O),huge),new ExactLinearProgram.Constraint(Map.of(0,O.negate(),2,O.negate()),huge.negate()),new ExactLinearProgram.Constraint(Map.of(1,O.negate(),2,O),Z));var b=budget();try(var solver=new CountNetwork(rows,new BigInteger[]{Z,Z,Z},new BigInteger[]{huge,huge,huge},b)){while(!solver.step()){}if(solver.counts()==null||!valid(rows,solver.counts()))throw new AssertionError("BigInteger flow");}
 for(int stop=1;stop<512;stop++){int[]calls={0};int limit=stop;var budget=new PlanningBudget(0,20000000,256L<<20,()->++calls[0]>=limit,System::nanoTime);try(var solver=new CountNetwork(rows,new BigInteger[]{Z,Z,Z},new BigInteger[]{huge,huge,huge},budget)){while(!solver.step()){}}catch(java.util.concurrent.CancellationException expected){}if(budget.reservedBytes()!=0)throw new AssertionError("cancel leak "+stop);}
 System.out.println("PASS exact min-cost flow models=5000 assignments="+checked+" SAT="+sat+" UNSAT="+unsat+" Farkas mincuts, 100-bit offsets, 130-bit capacities, 511 cancellation boundaries");
 }
}
