package org.cgse.core;
import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.*;
public class CatalogIndexClockProbe {
 static List<GraphRecipe<String>> catalog(){var r=new ArrayList<GraphRecipe<String>>();for(int i=0;i<500;i++)r.add(new GraphRecipe<>("r"+i,"r"+i,List.of(new GraphRecipe.Slot<>("k"+i,1)),Map.of("k"+(i+1),2L)));return List.copyOf(r);}
 static int hash(GraphCatalogIndex<String>index,List<GraphRecipe<String>>recipes){int h=1;for(var r:recipes){var p=index.ports(r);h=31*h+Arrays.hashCode(p.inputs());h=31*h+Arrays.hashCode(p.outputs());h=31*h+Arrays.hashCode(p.inputAmounts());h=31*h+Arrays.hashCode(p.outputAmounts());h=31*h+Arrays.hashCode(p.physicalOutputs());h=31*h+Arrays.hashCode(p.changed());h=31*h+Arrays.hashCode(p.changes());}for(int i=0;i<index.resourceCount();i++){var k=index.resource(i);h=31*h+Arrays.hashCode(index.consumers(k));h=31*h+Arrays.hashCode(index.producers(k));}return h;}
 public static void main(String[]args)throws Exception{var recipes=catalog();var executor=Executors.newSingleThreadExecutor();try{for(int mode=0;mode<3;mode++){var budget=new PlanningBudget(0,20_000_000,128L<<20,()->false,System::nanoTime);GraphCatalogIndex<String>result;try(var builder=new GraphCatalogIndex.Builder<>(recipes,budget)){for(int i=0;i<recipes.size();i++){int id=i;if(mode==2&&i%2==1)executor.submit(()->builder.add(recipes.get(id),id)).get();else builder.add(recipes.get(i),i);if(mode>0)budget.charge(1000);}boolean done=false;int turn=0;while(!done){done=mode==2&&turn%2==1?executor.submit(()->builder.step()).get():builder.step();if(mode>0)budget.charge(1000);turn++;}result=builder.result();}if(budget.reservedBytes()!=0)throw new AssertionError("leak mode"+mode);System.out.println("mode="+mode+" index="+(result==null?"DECLINED":hash(result,recipes))+" global_work="+budget.nodes());if(args.length==0&&result==null)throw new AssertionError("declined "+mode);}
 for(int cap=1;cap<=300;cap++){var checks=new AtomicInteger();int limit=cap;var budget=new PlanningBudget(0,20_000_000,128L<<20,()->checks.incrementAndGet()>limit,System::nanoTime);try(var builder=new GraphCatalogIndex.Builder<>(recipes,budget)){for(int i=0;i<recipes.size();i++)builder.add(recipes.get(i),i);while(!builder.step()){};}catch(CancellationException expected){}if(budget.reservedBytes()!=0)throw new AssertionError("cancel leak "+cap);}
 for(long limit:new long[]{1000,20000,50000}){var budget=new PlanningBudget(0,limit,128L<<20,()->false,System::nanoTime);try(var builder=new GraphCatalogIndex.Builder<>(recipes,budget)){for(int i=0;i<recipes.size();i++)builder.add(recipes.get(i),i);while(!builder.step()){};}catch(PlanningBudget.Exhausted expected){}if(budget.reservedBytes()!=0)throw new AssertionError("cap leak "+limit);}System.out.println("cancellation=300 budget_caps=3 PASS");}finally{executor.shutdownNow();}}
}
