package org.cgse.core;
import java.math.*;import java.util.*;
public final class RevisedOracle {
 static final BigInteger Z=BigInteger.ZERO,O=BigInteger.ONE;
 static PlanningBudget budget(){return new PlanningBudget(0,20000000,256L<<20,()->false,System::nanoTime);}
 static BigInteger det(BigInteger[][]a){int n=a.length;if(n==1)return a[0][0];BigInteger d=Z;for(int col=0;col<n;col++){var b=new BigInteger[n-1][n-1];for(int i=1;i<n;i++)for(int j=0,k=0;j<n;j++)if(j!=col)b[i-1][k++]=a[i][j];var x=a[0][col].multiply(det(b));d=col%2==0?d.add(x):d.subtract(x);}return d;}
 static ExactRational best;static int vertices;
 static void vertices(List<ExactLinearProgram.Constraint>rows,BigInteger[]objective,int[]selected,int at,int start){int n=objective.length;if(at<n){for(int r=start;r<=rows.size()-(n-at);r++){selected[at]=r;vertices(rows,objective,selected,at+1,r+1);}return;}var a=new BigInteger[n][n];for(int i=0;i<n;i++)for(int j=0;j<n;j++)a[i][j]=rows.get(selected[i]).terms().getOrDefault(j,Z);var d=det(a);if(d.signum()==0)return;var p=new ExactRational[n];for(int j=0;j<n;j++){var b=new BigInteger[n][n];for(int i=0;i<n;i++)for(int k=0;k<n;k++)b[i][k]=k==j?rows.get(selected[i]).upper():a[i][k];var numerator=det(b);p[j]=new ExactRational(d.signum()<0?numerator.negate():numerator,d.abs());}for(var row:rows){var sum=ExactRational.ZERO;for(var e:row.terms().entrySet())sum=sum.add(ExactRational.of(e.getValue()).multiply(p[e.getKey()]));if(sum.compareTo(ExactRational.of(row.upper()))>0)return;}vertices++;var value=ExactRational.ZERO;for(int j=0;j<n;j++)value=value.add(p[j].multiply(ExactRational.of(objective[j])));if(best==null||best.compareTo(value)<0)best=value;}
 public static void main(String[]args){var random=new Random(984730);int sat=0,unsat=0;for(int test=0;test<2000;test++){int n=1+random.nextInt(3);var rows=new ArrayList<ExactLinearProgram.Constraint>();var objective=new BigInteger[n];for(int i=0;i<n;i++){rows.add(new ExactLinearProgram.Constraint(Map.of(i,O),BigInteger.valueOf(1+random.nextInt(8))));rows.add(new ExactLinearProgram.Constraint(Map.of(i,O.negate()),Z));objective[i]=BigInteger.valueOf(random.nextInt(9)-4);}for(int r=0;r<1+random.nextInt(5);r++){var terms=new LinkedHashMap<Integer,BigInteger>();for(int i=0;i<n;i++){var c=BigInteger.valueOf(random.nextInt(13)-6);if(c.signum()!=0)terms.put(i,c);}rows.add(new ExactLinearProgram.Constraint(terms,BigInteger.valueOf(random.nextInt(16)-6)));}best=null;vertices(rows,objective,new int[n],0,0);var b=budget();var journal=new CountProof.Journal(8L<<20);b.proofJournal(journal);try(var p=new ExactRevisedProgram(n,rows,objective,b)){while(!p.step()){}if(best==null){unsat++;if(p.result()!=ExactLinearProgram.Result.INFEASIBLE)throw new AssertionError("missed UNSAT "+test+" "+b.diagnostics());}else{sat++;if(p.result()!=ExactLinearProgram.Result.OPTIMAL)throw new AssertionError("missed optimum "+test+" "+b.diagnostics());var actual=ExactRational.ZERO;for(int j=0;j<n;j++)actual=actual.add(p.point()[j].multiply(ExactRational.of(objective[j])));if(!actual.equals(best))throw new AssertionError("wrong optimum "+test);}}for(var proof:journal.entries())if(CountProof.verify(proof,2000000)!=CountProof.Verdict.VERIFIED)throw new AssertionError("certificate");if(b.reservedBytes()!=0)throw new AssertionError("leak");}
 int n=400;var rows=new ArrayList<ExactLinearProgram.Constraint>();var goal=new LinkedHashMap<Integer,BigInteger>();var objective=new BigInteger[n];Arrays.fill(objective,O.negate());for(int i=0;i<n;i++){rows.add(new ExactLinearProgram.Constraint(Map.of(i,O),O));rows.add(new ExactLinearProgram.Constraint(Map.of(i,BigInteger.TWO),BigInteger.TWO));goal.put(i,O.negate());}rows.add(new ExactLinearProgram.Constraint(goal,O.negate()));var b=budget();try(var p=new ExactLinearProgram(n,rows,objective,b)){while(!p.step()){}if(p.result()!=ExactLinearProgram.Result.OPTIMAL)throw new AssertionError("sparse admission "+b.diagnostics());System.out.println("SPARSE 400 variables 801 rows "+b.diagnostics()+" peak="+b.peakBytes());}if(b.reservedBytes()!=0)throw new AssertionError("delegation leak");
 for(int stop=1;stop<384;stop++){int[]calls={0};int limit=stop;var budget=new PlanningBudget(0,20000000,256L<<20,()->++calls[0]>=limit,System::nanoTime);try(var p=new ExactRevisedProgram(2,List.of(new ExactLinearProgram.Constraint(Map.of(0,O.negate(),1,O.negate()),BigInteger.TWO.negate()),new ExactLinearProgram.Constraint(Map.of(0,O,1,BigInteger.TWO),BigInteger.valueOf(3))),new BigInteger[]{O,O},budget)){while(!p.step()){}}catch(java.util.concurrent.CancellationException expected){}if(budget.reservedBytes()!=0)throw new AssertionError("cancel leak "+stop);}
 System.out.println("PASS sparse revised LP cases=2000 SAT="+sat+" UNSAT="+unsat+" independently enumerated feasible vertices="+vertices+" exact optima/Farkas; 383 cancellations");}
}
