package org.cgse.core;
import java.math.*;import java.util.*;import java.nio.file.*;
public final class AuditOracle {
 static final BigInteger Z=BigInteger.ZERO,O=BigInteger.ONE;
 static boolean valid(List<ExactLinearProgram.Constraint> rows,BigInteger[] x){for(var r:rows){var s=Z;for(var e:r.terms().entrySet())s=s.add(e.getValue().multiply(x[e.getKey()]));if(s.compareTo(r.upper())>0)return false;}return true;}
 static PlanningBudget budget(){return new PlanningBudget(0,20000000,256L<<20,()->false,System::nanoTime);}
 public static void main(String[]args)throws Exception {var random=new Random(929815);long checked=0;int sat=0,unsat=0,cuts=0;CountProof.Clique saved=null;
 for(int test=0;test<4000;test++){int n=2+random.nextInt(5),total=1;boolean binary=test%2==0;var lo=new BigInteger[n];var hi=new BigInteger[n];var planted=new BigInteger[n];int[]domain=new int[n];
  for(int i=0;i<n;i++){lo[i]=test%17==0?O.shiftLeft(90):BigInteger.valueOf(random.nextInt(4));domain[i]=binary?2:1+random.nextInt(4);hi[i]=lo[i].add(BigInteger.valueOf(domain[i]-1));planted[i]=lo[i].add(BigInteger.valueOf(random.nextInt(domain[i])));total*=domain[i];}
  var rows=new ArrayList<ExactLinearProgram.Constraint>();for(int r=0;r<3+random.nextInt(8);r++){var terms=new LinkedHashMap<Integer,BigInteger>();BigInteger rhs=BigInteger.valueOf(random.nextInt(5)-2);for(int i=0;i<n;i++){var a=BigInteger.valueOf(random.nextInt(13)-6);if(test%19==0)a=a.shiftLeft(130);if(a.signum()!=0)terms.put(i,a);rhs=rhs.add(a.multiply(planted[i]));}rows.add(new ExactLinearProgram.Constraint(terms,rhs));}
  var solutions=new ArrayList<BigInteger[]>();for(int code=0;code<total;code++){int c=code;var x=lo.clone();for(int i=0;i<n;i++){x[i]=x[i].add(BigInteger.valueOf(c%domain[i]));c/=domain[i];}checked++;if(valid(rows,x))solutions.add(x);}
  var b=budget();var journal=new CountProof.Journal(32L<<20);b.proofJournal(journal);try(var solver=new CountSeparator(rows,lo,hi,b)){while(!solver.step()){}var x=solver.counts();if(solutions.isEmpty()){unsat++;if(x!=null||!solver.infeasible())throw new AssertionError("separator missed UNSAT "+test+" "+b.diagnostics());}else{sat++;if(solver.infeasible()||x==null||!valid(rows,x))throw new AssertionError("separator missed SAT "+test);}}
  for(var proof:journal.entries())if(CountProof.verify(proof,20000000)!=CountProof.Verdict.VERIFIED){System.out.println("FAILED "+test+" verdict="+CountProof.verify(proof,20000000)+" proof="+proof);throw new AssertionError("invalid proof");}
  try(var solver=new CountCliques(rows,lo,hi,null,b)){while(!solver.step()){}cuts+=solver.cuts().size();for(var x:solutions)if(!valid(solver.cuts(),x))throw new AssertionError("clique removed solution "+test);for(var proof:solver.proofs()){if(CountProof.verify(proof,2000000)!=CountProof.Verdict.VERIFIED)throw new AssertionError("bad clique");saved=proof;var bad=new CountProof.Clique(proof.scope(),proof.variables(),proof.axioms(),proof.lower(),proof.upper(),proof.literals(),proof.witnesses(),new CountProof.Row(proof.consequence().terms(),proof.consequence().upper().subtract(O)));if(CountProof.verify(bad,2000000)!=CountProof.Verdict.INVALID)throw new AssertionError("tampering");}}
  if(b.reservedBytes()!=0)throw new AssertionError("leak "+test+" "+b.reservedBytes());
 }
 if(saved==null||cuts==0)throw new AssertionError("no cuts tested");var journal=new CountProof.Journal(4L<<20);journal.add(saved);var path=Path.of(args[0]);journal.write(path);var reread=CountProof.read(path);if(reread.cliques().size()!=1||CountProof.verify(reread.cliques().get(0),2000000)!=CountProof.Verdict.VERIFIED)throw new AssertionError("CGP5 roundtrip");
 var rows=List.of(new ExactLinearProgram.Constraint(Map.of(0,BigInteger.valueOf(6),1,BigInteger.valueOf(7),2,BigInteger.valueOf(8)),BigInteger.TEN));var lo=new BigInteger[]{Z,Z,Z};var hi=new BigInteger[]{O,O,O};for(int type=0;type<2;type++)for(int stop=1;stop<384;stop++){int[] calls={0};int limit=stop;var b=new PlanningBudget(0,20000000,256L<<20,()->++calls[0]>=limit,System::nanoTime);try{if(type==0)try(var solver=new CountSeparator(rows,lo,hi,b)){while(!solver.step()){}}else try(var solver=new CountCliques(rows,lo,hi,null,b)){while(!solver.step()){}}}catch(java.util.concurrent.CancellationException expected){}if(b.reservedBytes()!=0)throw new AssertionError("cancel leak "+type+" "+stop);}
 System.out.println("PASS separator+clique models=4000 assignments="+checked+" SAT="+sat+" UNSAT="+unsat+" cuts="+cuts+" exact certificates, shifted/130-bit coefficients, tamper rejection, CGP5, 766 cancellation boundaries");
 }
}
