package org.cgse.core;
import java.util.*;import java.math.BigInteger;
public class WideCutProbe {
 static BigInteger b(long n){return BigInteger.valueOf(n);} public static void main(String[]args){int n=1699;var rows=List.of(new ExactLinearProgram.Constraint(Map.of(53,b(1),146,b(-1),152,b(1),1204,b(1)),b(0)),new ExactLinearProgram.Constraint(Map.of(146,b(1),152,b(-1),333,b(-1)),b(0)));var cut=new CountLpLearning.Cut(new ExactLinearProgram.Constraint(Map.of(53,b(1),1204,b(1),333,b(-1)),b(0)),Map.of(0,b(1),1,b(1)),b(1));var lo=new BigInteger[n];var hi=new BigInteger[n];Arrays.fill(lo,b(0));var budget=new PlanningBudget(0,2000000,64L<<20,()->false,System::nanoTime);
 try(var models=CountModelViews.create(rows,lo,hi,budget);var destination=new CountLcg(rows,lo,hi,budget,20000)){models.publishCuts(models.available().get(0),List.of(cut),0,new Object());if(models.cutVersion()!=1)throw new AssertionError("wide admission failed");if(models.importCuts(models.available().get(0),0,destination,destination)!=1)throw new AssertionError("wide import failed");}
 if(budget.reservedBytes()!=0)throw new AssertionError("model leak");
 var expressions=new ArrayList<CountMapping.Expression>();for(int i=0;i<n;i++)expressions.add(new CountMapping.Expression(Map.of(i,b(2)),b(3)));var map=new CountMapping(expressions);var shape=new CountModelViews.Shape(n,7,1,n);var source=new CountModelViews.View("source",rows,lo,hi,shape,null,CountModelViews.Semantics.EQUIVALENT,map);var target=new CountModelViews.View("target",List.of(),lo,hi,shape,null,CountModelViews.Semantics.EQUIVALENT,null);
 try(var pool=CountViewCuts.create(budget)){pool.publish(source,List.of(cut),0,new Object());var received=new ArrayList<ExactLinearProgram.Constraint>();if(pool.transfer(target,0,new Object(),row->{received.add(row);return true;})!=1)throw new AssertionError("no mapped cut");if(!received.get(0).equals(new ExactLinearProgram.Constraint(cut.row().terms(),b(3))))throw new AssertionError("wrong lift "+received);}
 if(budget.reservedBytes()!=0)throw new AssertionError("mapping leak");var proof=new CountProof.Derivation("wide1699",n,rows.stream().map(CountProof::row).toList(),List.of(new CountProof.Combination(cut.parents(),cut.divisor(),CountProof.row(cut.row()))));if(CountProof.verify(proof,1000000)!=CountProof.Verdict.VERIFIED)throw new AssertionError("certificate rejected");System.out.println("1699-coordinate sparse cut admission/lift/import/proof PASS; work="+budget.nodes()+" peak="+budget.peakBytes()); }
}
