package org.cgse.core;
import java.math.*;import java.util.*;
public class FactorOracle {
 static final BigInteger Z=BigInteger.ZERO,O=BigInteger.ONE;
 static PlanningBudget budget(){return new PlanningBudget(0,20000000,256L<<20,()->false,System::nanoTime);}
 static void check(List<Map<Integer,ExactRational>> columns,ExactRational[] x,ExactRational[] rhs,boolean transpose){var got=new ExactRational[x.length];Arrays.fill(got,ExactRational.ZERO);for(int j=0;j<x.length;j++)for(var e:columns.get(j).entrySet()){int i=e.getKey();int at=transpose?j:i;got[at]=got[at].add(e.getValue().multiply(x[transpose?i:j]));}if(!Arrays.equals(got,rhs))throw new AssertionError("factor solve mismatch");}
 public static void main(String[]args){var random=new Random(917227);int ready=0;for(int sample=0;sample<1000;sample++){int n=2+random.nextInt(18);List<Map<Integer,ExactRational>> columns=new ArrayList<>();var rhs=new ExactRational[n];for(int j=0;j<n;j++){Map<Integer,ExactRational> column=new TreeMap<>();for(int i=0;i<n;i++)if(random.nextInt(4)==0||i==j)column.put(i,ExactRational.of(BigInteger.valueOf(random.nextInt(19)-9)));columns.add(column);rhs[j]=ExactRational.of(BigInteger.valueOf(random.nextInt(19)-9));}var b=budget();try(var f=ExactSparseFactor.build(columns,b,1000000)){if(f!=null){ready++;var x=rhs.clone();f.solve(x,b::check);check(columns,x,rhs,false);x=rhs.clone();f.transpose(x,b::check);check(columns,x,rhs,true);}}if(b.reservedBytes()!=0)throw new AssertionError("factor leak");}
 int n=160;List<ExactLinearProgram.Constraint> rows=new ArrayList<>();var objective=new BigInteger[n];Arrays.fill(objective,O);for(int i=0;i<n;i++)rows.add(new ExactLinearProgram.Constraint(Map.of(i,O),O));var b=budget();try(var p=new ExactRevisedProgram(n,rows,objective,b)){while(!p.step()){}if(p.result()!=ExactLinearProgram.Result.OPTIMAL||Arrays.stream(p.point()).anyMatch(x->!x.equals(ExactRational.ONE)))throw new AssertionError("long pivots "+b.diagnostics());System.out.println(b.diagnostics());if(!b.diagnostics().contains("refactors=2"))throw new AssertionError("no refactor exercised");}if(b.reservedBytes()!=0)throw new AssertionError("refactor leak");
 var columns=List.of(Map.of(0,ExactRational.ONE,1,ExactRational.ONE),Map.of(0,ExactRational.ONE,1,ExactRational.of(BigInteger.TWO)));for(int stop=1;stop<256;stop++){int[] calls={0};int limit=stop;var budget=new PlanningBudget(0,20000000,256L<<20,()->++calls[0]>=limit,System::nanoTime);try(var f=ExactSparseFactor.build(columns,budget,100000)){}catch(java.util.concurrent.CancellationException expected){}if(budget.reservedBytes()!=0)throw new AssertionError("cancel leak "+stop);}
 System.out.println("PASS exact sparse PLU matrices=1000 nonsingular="+ready+" primal/transpose solves, 160-pivot refactor, 255 cancellation boundaries");}
}
