package org.cgse.core;
import java.math.*;import java.util.*;
public final class ScheduleOracle {
 static final BigInteger Z=BigInteger.ZERO,O=BigInteger.ONE;
 static PlanningBudget budget(){return new PlanningBudget(0,20000000,256L<<20,()->false,System::nanoTime);}
 static boolean bfs(List<GraphRecipe<String>> recipes,int[] total,Map<String,Long> initial){var seen=new HashSet<List<Integer>>();var queue=new ArrayDeque<int[]>();queue.add(total);while(!queue.isEmpty()){int[]remaining=queue.removeFirst();if(Arrays.stream(remaining).allMatch(x->x==0))return true;var state=Arrays.stream(remaining).boxed().toList();if(!seen.add(state))continue;var held=new HashMap<String,Long>(initial);for(int r=0;r<recipes.size();r++){long used=total[r]-remaining[r];for(var e:recipes.get(r).inputs().entrySet())held.merge(e.getKey(),-e.getValue()*used,Long::sum);for(var e:recipes.get(r).outputs().entrySet())held.merge(e.getKey(),e.getValue()*used,Long::sum);}for(int r=0;r<recipes.size();r++){if(remaining[r]==0)continue;boolean ok=true;for(var e:recipes.get(r).inputs().entrySet())if(held.getOrDefault(e.getKey(),0L)<e.getValue())ok=false;if(ok){int[]next=remaining.clone();next[r]--;queue.add(next);}}}return false;}
 public static void main(String[]args){var rng=new Random(279515);int sat=0,unsat=0,guards=0,unknown=0;for(int test=0;test<1000;test++){int n=2+rng.nextInt(4),resources=2+rng.nextInt(3);var recipes=new ArrayList<GraphRecipe<String>>();for(int r=0;r<n;r++){var inputs=new ArrayList<GraphRecipe.Slot<String>>();var outputs=new LinkedHashMap<String,Long>();outputs.put("Q",1L);for(int k=0;k<resources;k++){long in=rng.nextInt(3),out=rng.nextInt(3);if(in>0)inputs.add(new GraphRecipe.Slot<>("K"+k,in));if(out>0)outputs.put("K"+k,out);}recipes.add(new GraphRecipe<>("r"+r,"r"+r,inputs,outputs));}var stock=new LinkedHashMap<String,Long>();for(int k=0;k<resources;k++)stock.put("K"+k,(long)rng.nextInt(4));var compiler=new GraphCompiler<>(recipes);var b=budget();var journal=new CountProof.Journal(32L<<20);b.proofJournal(journal);try(var model=RecipeCountModel.create(compiler,"Q",1,stock,Map.of(),Set.of(),Set.of(),false,b)){int[]total=new int[n];BigInteger[]counts=new BigInteger[n];for(int r=0;r<n;r++){total[r]=rng.nextInt(3);counts[r]=BigInteger.valueOf(total[r]);}boolean feasible=bfs(model.recipes,total,stock);try(var p=new CountBoundedSchedule<>(model,counts,b)){while(!p.step()){}if(p.result()==CountSchedule.Result.UNKNOWN)unknown++;else if(feasible){sat++;if(p.result()!=CountSchedule.Result.WITNESS)throw new AssertionError("false dead schedule "+test+" "+b.diagnostics());}else{unsat++;if(p.result()!=CountSchedule.Result.DEAD)throw new AssertionError("false schedule "+test+" "+b.diagnostics());}}try(var p=new CountExecution<>(model,b)){if(feasible){var point=Arrays.stream(counts).map(ExactRational::of).toArray(ExactRational[]::new);for(var proof:p.proofs()){guards++;if(proof.guard().violated(point,b))throw new AssertionError("startup pool excluded executable counts "+test);}}}}for(var proof:journal.entries())if(CountProof.verify(proof,20000000)!=CountProof.Verdict.VERIFIED)throw new AssertionError("schedule proof "+test);if(b.reservedBytes()!=0)throw new AssertionError("leak "+b.reservedBytes());}
 System.out.println("PASS bounded SAT schedule networks=1000 BFS SAT="+sat+" UNSAT="+unsat+" UNKNOWN="+unknown+" valid startup guards="+guards+" complete fixed-multiset proofs");
 }
}
