package org.cgse.core;
import java.math.*;import java.util.*;
public class AffineFacesOracle {
 static final BigInteger Z=BigInteger.ZERO,O=BigInteger.ONE;
 public static void main(String[]args){var rng=new Random(962801);int found=0;
  for(int t=0;t<1600;t++){int n=4+rng.nextInt(5);var lo=new BigInteger[n];var hi=new BigInteger[n];var target=new BigInteger[n];for(int i=0;i<n;i++){lo[i]=Z;hi[i]=BigInteger.valueOf(3+rng.nextInt(12));target[i]=BigInteger.valueOf(rng.nextInt(hi[i].intValue()+1));}var rows=new ArrayList<ExactLinearProgram.Constraint>();for(int r=0;r<3+rng.nextInt(6);r++){var a=new TreeMap<Integer,BigInteger>();var rhs=Z;for(int i=0;i<n;i++){var v=BigInteger.valueOf(-(2+rng.nextInt(31)));a.put(i,v);rhs=rhs.add(v.multiply(target[i]));}rhs=rhs.add(BigInteger.valueOf(rng.nextInt(4)));rows.add(new ExactLinearProgram.Constraint(a,rhs));}if(t%3==0){var sum=new TreeMap<Integer,BigInteger>();var rhs=Z;for(int i=0;i<n;i++){sum.put(i,O);rhs=rhs.add(target[i]);}AffineOracle.equation(rows,sum,rhs);}if(t%7==0)rows.add(new ExactLinearProgram.Constraint(Map.of(0,O,1,O),target[0].add(target[1])));var b=AffineOracle.budget();try(var p=new CountAffineLattice(rows,lo,hi,b)){while(!p.step()){}if(p.counts()!=null){found++;if(!AffineOracle.valid(rows,lo,hi,p.counts()))throw new AssertionError("invalid trial-face witness "+t);}}if(b.reservedBytes()!=0)throw new AssertionError("leak");}
  var rows=new ArrayList<ExactLinearProgram.Constraint>();AffineOracle.equation(rows,Map.of(0,BigInteger.TWO,1,BigInteger.TWO),BigInteger.TEN);AffineOracle.equation(rows,Map.of(2,BigInteger.valueOf(3),3,BigInteger.valueOf(3)),BigInteger.valueOf(15));rows.add(new ExactLinearProgram.Constraint(Map.of(0,BigInteger.valueOf(-7),2,BigInteger.valueOf(-11)),BigInteger.valueOf(-1)));var lo=new BigInteger[]{Z,Z,Z,Z};var hi=new BigInteger[]{BigInteger.TEN,BigInteger.TEN,BigInteger.TEN,BigInteger.TEN};var b=AffineOracle.budget();try(var p=new CountDiophantine(rows,lo,hi,b)){while(!p.step()){}if(p.counts()==null||!AffineOracle.valid(rows,lo,hi,p.counts()))throw new AssertionError("trial equality hid exact witness");}if(b.reservedBytes()!=0)throw new AssertionError("fallback leak");
  int[]checks={0};var cancel=new PlanningBudget(0,20000000,256L<<20,()->++checks[0]>=300,System::nanoTime);try(var p=new CountAffineLattice(rows,lo,hi,cancel)){while(!p.step()){}}catch(java.util.concurrent.CancellationException ok){}if(cancel.reservedBytes()!=0)throw new AssertionError("trial cancel leak");
  System.out.println("PASS 1600 trial-face proposals checked against original inequalities; witnesses="+found+"; rejected trial face preserves true equality witness; lifecycle closed");
 }
}
