package org.cgse.core;
import java.math.BigInteger;import java.util.*;
/** Local experiment: disjoint necessary AMOs strengthen grouped covers and exact lifting. */
final class CountGubCoverPrototype implements AutoCloseable{
 private static final class Stop extends RuntimeException{static final Stop ONE=new Stop();private Stop(){super(null,null,false,false);}}
 record Item(int id,int group,BigInteger weight,ExactRational value){}
 record Level(int group,BigInteger weight,ExactRational value,List<Item> members){}
 final List<ExactLinearProgram.Constraint> rows;final BigInteger[] lo,hi;final ExactRational[] point;final PlanningBudget budget;final long allowance;long work,memory;final List<ExactLinearProgram.Constraint> cuts=new ArrayList<>();final Map<ExactLinearProgram.Constraint,ExactRational> scores=new HashMap<>();final Map<Integer,List<Integer>> members=new LinkedHashMap<>();int[] groups;
 CountGubCoverPrototype(List<ExactLinearProgram.Constraint> rows,BigInteger[] lo,BigInteger[] hi,ExactRational[] point,PlanningBudget budget,long allowance){this.rows=rows;this.lo=lo;this.hi=hi;this.point=point;this.budget=budget;this.allowance=Math.min(allowance,budget.remainingWork()/16);}
 static List<ExactLinearProgram.Constraint> separate(List<ExactLinearProgram.Constraint> rows,BigInteger[] lo,BigInteger[] hi,ExactRational[] point,PlanningBudget budget,long allowance){try(var p=new CountGubCoverPrototype(rows,lo,hi,point,budget,allowance)){try{p.run();}catch(Stop stop){}if(!p.cuts.isEmpty())System.err.println("GUB deficits="+p.cuts.size()+" work="+p.work);return List.copyOf(p.cuts);}}
 void tick(){if(work>=allowance)throw Stop.ONE;budget.check();work++;}
 void run(){if(lo.length>128||rows.size()>512||allowance<2048)return;long bytes=65536+2048L*lo.length+128L*rows.size();if(!budget.tryReserve(bytes))return;memory=bytes;groups=new int[lo.length];Arrays.fill(groups,-1);int next=0;
  var normalized=new ArrayList<ExactLinearProgram.Constraint>();for(var row:rows){for(var ignored:row.terms().entrySet())tick();normalized.add(CountReduction.normalize(row));}
  for(var row:normalized){BigInteger minimum=BigInteger.ZERO;var ids=new ArrayList<Integer>();boolean okay=true;for(var t:row.terms().entrySet()){tick();int id=t.getKey();BigInteger end=t.getValue().signum()>0?lo[id]:hi[id];if(end==null){okay=false;break;}minimum=minimum.add(t.getValue().multiply(end));if(t.getValue().equals(BigInteger.ONE)&&hi[id]!=null&&hi[id].subtract(lo[id]).equals(BigInteger.ONE)&&groups[id]<0)ids.add(id);}if(okay&&row.upper().subtract(minimum).equals(BigInteger.ONE)&&ids.size()>1){for(int id:ids)groups[id]=next;next++;}}
  for(int i=0;i<groups.length;i++)if(groups[i]<0)groups[i]=next++;
  for(int i=0;i<groups.length;i++)if(hi[i]!=null&&hi[i].subtract(lo[i]).equals(BigInteger.ONE))members.computeIfAbsent(groups[i],g->new ArrayList<>()).add(i);
  var ordered=new ArrayList<>(normalized);ordered.sort(Comparator.comparingInt((ExactLinearProgram.Constraint r)->r.terms().size()).reversed());
  for(var row:ordered){if(row.terms().size()<2||row.terms().size()>128)continue;boolean okay=true;BigInteger minimum=BigInteger.ZERO;Map<Integer,List<Item>> byGroup=new LinkedHashMap<>();List<Item> all=new ArrayList<>();for(var t:row.terms().entrySet()){tick();int id=t.getKey();boolean binary=hi[id]!=null&&hi[id].subtract(lo[id]).equals(BigInteger.ONE);BigInteger end=binary||t.getValue().signum()>=0?lo[id]:hi[id];if(end==null){okay=false;break;}minimum=minimum.add(t.getValue().multiply(end));}if(!okay)continue;
   for(var group:members.entrySet()){BigInteger least=BigInteger.ZERO;boolean involved=false;for(int id:group.getValue()){tick();BigInteger coefficient=row.terms().getOrDefault(id,BigInteger.ZERO);least=least.min(coefficient);if(coefficient.signum()!=0)involved=true;}if(!involved)continue;minimum=minimum.add(least);List<Item> options=new ArrayList<>();ExactRational none=ExactRational.ONE;for(int id:group.getValue()){ExactRational value=point[id].subtract(ExactRational.of(lo[id]));if(value.signum()<0||value.compareTo(ExactRational.ONE)>0){okay=false;break;}none=none.subtract(value);Item item=new Item(id,group.getKey(),row.terms().getOrDefault(id,BigInteger.ZERO).subtract(least),value);options.add(item);all.add(item);}if(!okay||none.signum()<0){okay=false;break;}Item item=new Item(-group.getKey()-1,group.getKey(),least.negate(),none);options.add(item);all.add(item);byGroup.put(group.getKey(),options);}
   BigInteger capacity=row.upper().subtract(minimum);if(!okay||capacity.signum()<0||all.size()<2)continue;
   List<List<Level>> choices=new ArrayList<>();for(var entry:byGroup.entrySet()){List<Level> levels=new ArrayList<>();Set<BigInteger> weights=new TreeSet<>();for(Item item:entry.getValue())if(item.weight().signum()>0)weights.add(item.weight());for(BigInteger weight:weights){List<Item> subset=new ArrayList<>();ExactRational value=ExactRational.ZERO;for(Item item:entry.getValue()){tick();if(item.weight().compareTo(weight)>=0){subset.add(item);value=value.add(item.value());}}levels.add(new Level(entry.getKey(),weight,value,subset));}if(!levels.isEmpty())choices.add(levels);}
   for(int pass=0;pass<3;pass++){List<Level> levels=new ArrayList<>();for(var options:choices){Level best=options.get(0);for(Level option:options){tick();if(compare(option,best,pass)<0)best=option;}levels.add(best);}final int order=pass;levels.sort((a,b)->compare(a,b,order));List<Level> cover=new ArrayList<>();BigInteger weight=BigInteger.ZERO;for(Level level:levels){tick();cover.add(level);weight=weight.add(level.weight());if(weight.compareTo(capacity)>0)break;}if(weight.compareTo(capacity)<=0)continue;cover.sort(Comparator.comparing(Level::value));for(var it=cover.iterator();it.hasNext();){Level level=it.next();tick();if(weight.subtract(level.weight()).compareTo(capacity)>0){weight=weight.subtract(level.weight());it.remove();}}
    Map<Item,Integer> coefficients=new LinkedHashMap<>();for(Level level:cover)for(Item item:level.members())coefficients.put(item,1);int rhs=maximum(coefficients,capacity,null);offer(coefficients,rhs);List<Item> lift=new ArrayList<>(all);lift.sort(Comparator.comparing(Item::value).reversed());for(Item extra:lift){if(coefficients.containsKey(extra))continue;tick();int max=maximum(coefficients,capacity,extra);int coefficient=rhs-max;if(coefficient>0)coefficients.put(extra,coefficient);offer(coefficients,rhs);}
   }
  }
 }
 int compare(Level a,Level b,int mode){int c;if(mode==0)c=ExactRational.ONE.subtract(a.value()).multiply(ExactRational.of(b.weight())).compareTo(ExactRational.ONE.subtract(b.value()).multiply(ExactRational.of(a.weight())));else if(mode==1)c=b.value().compareTo(a.value());else c=b.weight().compareTo(a.weight());return c!=0?c:Integer.compare(a.group(),b.group());}
 int maximum(Map<Item,Integer> coefficients,BigInteger capacity,Item fixed){BigInteger available=fixed==null?capacity:capacity.subtract(fixed.weight());if(available.signum()<0)return -1;Map<Integer,List<Map.Entry<Item,Integer>>> grouped=new LinkedHashMap<>();int total=0;for(var term:coefficients.entrySet()){tick();if(fixed!=null&&term.getKey().group()==fixed.group())continue;grouped.computeIfAbsent(term.getKey().group(),x->new ArrayList<>()).add(term);total+=term.getValue();}if(total>512)throw Stop.ONE;BigInteger[] dp=new BigInteger[total+1];dp[0]=BigInteger.ZERO;int used=0;for(var group:grouped.values()){BigInteger[] after=dp.clone();int most=0;for(var term:group){most=Math.max(most,term.getValue());for(int p=0;p<=used;p++){tick();if(dp[p]==null)continue;BigInteger w=dp[p].add(term.getKey().weight());int profit=p+term.getValue();if(after[profit]==null||w.compareTo(after[profit])<0)after[profit]=w;}}dp=after;used+=most;}for(int p=used;p>=0;p--){tick();if(dp[p]!=null&&dp[p].compareTo(available)<=0)return p;}return -1;}
 void offer(Map<Item,Integer> coefficients,int rhs){Map<Integer,BigInteger> terms=new LinkedHashMap<>();BigInteger bound=BigInteger.valueOf(rhs),norm=BigInteger.ZERO;ExactRational value=ExactRational.ZERO;for(var e:coefficients.entrySet()){tick();BigInteger a=BigInteger.valueOf(e.getValue());if(e.getKey().id()>=0)terms.merge(e.getKey().id(),a,BigInteger::add);else{bound=bound.subtract(a);for(int id:members.get(e.getKey().group()))terms.merge(id,a.negate(),BigInteger::add);}value=value.add(e.getKey().value().multiply(ExactRational.of(a)));}terms.values().removeIf(BigInteger.ZERO::equals);for(var e:terms.entrySet()){bound=bound.add(e.getValue().multiply(lo[e.getKey()]));norm=norm.add(e.getValue().multiply(e.getValue()));}ExactRational violation=value.subtract(ExactRational.of(BigInteger.valueOf(rhs)));if(violation.signum()<=0||norm.signum()==0)return;var cut=new ExactLinearProgram.Constraint(terms,bound);if(rows.contains(cut)||scores.containsKey(cut))return;var score=violation.multiply(violation).divide(ExactRational.of(norm));if(cuts.size()==4){var worst=cuts.get(0);for(var old:cuts)if(scores.get(old).compareTo(scores.get(worst))<0)worst=old;if(score.compareTo(scores.get(worst))<=0)return;cuts.remove(worst);scores.remove(worst);}cuts.add(cut);scores.put(cut,score);}
 public void close(){budget.release(memory);memory=0;}
}
