package org.cgse.core;
import java.math.*;import java.util.*;
public class MechanismsOracle {
 static final BigInteger Z=BigInteger.ZERO,O=BigInteger.ONE;
 static PlanningBudget b(){return new PlanningBudget(0,20000000,256L<<20,()->false,System::nanoTime);}
 static boolean valid(List<ExactLinearProgram.Constraint> rows,BigInteger[] x){return OptimizationOracle.valid(rows,x);}
 static List<BigInteger[]> values(int n,int width){var a=new ArrayList<BigInteger[]>();for(int c=0;c<(int)Math.pow(width,n);c++){int k=c;BigInteger[]x=new BigInteger[n];for(int j=0;j<n;j++){x[j]=BigInteger.valueOf(k%width);k/=width;}a.add(x);}return a;}
 static void proofs(CountProof.Journal j){for(var p:j.entries())if(CountProof.verify(p,2000000)!=CountProof.Verdict.VERIFIED)throw new AssertionError("certificate");for(var p:j.derivations())if(CountProof.verify(p,2000000)!=CountProof.Verdict.VERIFIED)throw new AssertionError("derivation");for(var p:j.rounding())if(CountProof.verify(p,2000000)!=CountProof.Verdict.VERIFIED)throw new AssertionError("rounding");}
 public static void main(String[]args){var rng=new Random(192819);int hc=0,rc=0,lr=0,softSolved=0,hallCuts=0;
 for(int t=0;t<1000;t++){int n=2+rng.nextInt(4);var rows=new ArrayList<ExactLinearProgram.Constraint>();var plant=values(n,3).get(rng.nextInt((int)Math.pow(3,n)));for(int r=0;r<2+rng.nextInt(4);r++){var terms=new TreeMap<Integer,BigInteger>();var opposite=new TreeMap<Integer,BigInteger>();var rhs=BigInteger.valueOf(t%3==0?1:0);for(int j=0;j<n;j++){var c=BigInteger.valueOf(rng.nextInt(9)-4);if(c.signum()!=0){terms.put(j,c);opposite.put(j,c.negate());rhs=rhs.add(c.multiply(plant[j]));}}rows.add(new ExactLinearProgram.Constraint(terms,rhs));rows.add(new ExactLinearProgram.Constraint(opposite,rhs.negate()));}var solutions=values(n,4).stream().filter(x->valid(rows,x)).toList();var b=b();var journal=new CountProof.Journal(32L<<20);b.proofJournal(journal);try(var p=new CountHermite(rows,n,b)){while(!p.step()){}hc+=p.cuts().size();for(var x:solutions)if(!valid(p.cuts(),x))throw new AssertionError("hermite cut "+t);}proofs(journal);if(b.reservedBytes()!=0)throw new AssertionError("hermite leak");}
 for(int t=0;t<1000;t++){int n=2+rng.nextInt(4);BigInteger[]low=new BigInteger[n],high=new BigInteger[n],cost=new BigInteger[n];Arrays.fill(low,Z);Arrays.fill(high,BigInteger.valueOf(3));for(int j=0;j<n;j++)cost[j]=BigInteger.valueOf(rng.nextInt(13)-3).shiftLeft(t%19==0?100:0);var rows=new ArrayList<ExactLinearProgram.Constraint>();for(int r=0;r<3;r++){var terms=new TreeMap<Integer,BigInteger>();for(int j=0;j<n;j++){var c=BigInteger.valueOf(rng.nextInt(9)-4);if(c.signum()!=0)terms.put(j,c);}rows.add(new ExactLinearProgram.Constraint(terms,BigInteger.valueOf(rng.nextInt(13)-4)));}var cutoff=BigInteger.valueOf(rng.nextInt(20)-5).shiftLeft(t%19==0?100:0);var objective=new TreeMap<Integer,BigInteger>();for(int j=0;j<n;j++)objective.put(j,cost[j]);var restricted=new ArrayList<>(rows);restricted.add(new ExactLinearProgram.Constraint(objective,cutoff));var solutions=values(n,4).stream().filter(x->valid(restricted,x)).toList();var b=b();var journal=new CountProof.Journal(32L<<20);b.proofJournal(journal);try(var p=new CountReducedCost(rows,low,high,cost,cutoff,b,500000)){while(!p.step()){}rc+=p.cuts().size();if(p.infeasible()&&!solutions.isEmpty())throw new AssertionError("rc false UNSAT");for(var x:solutions)if(!valid(p.cuts(),x))throw new AssertionError("rc cut");}proofs(journal);if(b.reservedBytes()!=0)throw new AssertionError("rc leak");}
 for(int t=0;t<1500;t++){int n=2+rng.nextInt(7);BigInteger[]low=new BigInteger[n],high=new BigInteger[n];Arrays.fill(low,Z);Arrays.fill(high,O);var rows=new ArrayList<ExactLinearProgram.Constraint>();for(int r=0;r<4+rng.nextInt(12);r++){var terms=new TreeMap<Integer,BigInteger>();for(int j=0;j<n;j++){var c=BigInteger.valueOf(rng.nextInt(31)-15);if(c.signum()!=0)terms.put(j,c);}rows.add(new ExactLinearProgram.Constraint(terms,BigInteger.valueOf(rng.nextInt(21)-5)));}boolean sat=values(n,2).stream().anyMatch(x->valid(rows,x));var b=b();var journal=new CountProof.Journal(32L<<20);b.proofJournal(journal);try(var p=new CountCdcl(rows,low,high,b,1000000,CountCdcl.Branching.LEARNING_RATE)){while(!p.step()){}if(p.counts()!=null){if(!sat||!valid(rows,p.counts()))throw new AssertionError("LRB false SAT");}else if(!p.infeasible()||sat)throw new AssertionError("LRB status "+t);lr++;}proofs(journal);if(b.reservedBytes()!=0)throw new AssertionError("LRB leak");}
 for(int t=0;t<500;t++){int n=2+rng.nextInt(3);BigInteger[]low=new BigInteger[n],high=new BigInteger[n];Arrays.fill(low,Z);Arrays.fill(high,BigInteger.TWO);var hard=new ArrayList<ExactLinearProgram.Constraint>();var soft=new ArrayList<CountSoftSearch.Soft>();for(int r=0;r<8+rng.nextInt(4);r++){var terms=new TreeMap<Integer,BigInteger>();for(int j=0;j<n;j++){var c=BigInteger.valueOf(rng.nextInt(7)-3);if(c.signum()!=0)terms.put(j,c);}var row=new ExactLinearProgram.Constraint(terms,BigInteger.valueOf(rng.nextInt(7)-2));if(r<2)hard.add(row);else soft.add(new CountSoftSearch.Soft(row,BigInteger.valueOf(1+rng.nextInt(9)).shiftLeft(t%17==0?90:0)));}BigInteger best=null;for(var x:values(n,3))if(valid(hard,x)){var c=Z;for(var s:soft)if(!valid(List.of(s.condition()),x))c=c.add(s.weight());if(best==null||c.compareTo(best)<0)best=c;}var b=b();try(var p=new CountCoreSoft(hard,low,high,soft,b,1000000)){while(!p.step()){}if(best!=null&&p.lowerBound().compareTo(best)>0)throw new AssertionError("core lower");if(p.infeasible()&&best!=null)throw new AssertionError("core false UNSAT");if(p.counts()!=null){if(best==null||!valid(hard,p.counts())||p.cost().compareTo(best)<0||p.optimal()&&!p.cost().equals(best))throw new AssertionError("core optimum");softSolved++;}}if(b.reservedBytes()!=0)throw new AssertionError("core leak");}
 for(int t=0;t<600;t++){int g=2+rng.nextInt(3),resources=2+rng.nextInt(4);var rows=new ArrayList<ExactLinearProgram.Constraint>();var caps=new ArrayList<Map<Integer,BigInteger>>();for(int r=0;r<resources;r++)caps.add(new TreeMap<>());int n=0;for(int group=0;group<g;group++){var pos=new TreeMap<Integer,BigInteger>();var neg=new TreeMap<Integer,BigInteger>();for(int r=0;r<resources;r++)if(rng.nextBoolean()){pos.put(n,O);neg.put(n,O.negate());caps.get(r).put(n,O);n++;}rows.add(new ExactLinearProgram.Constraint(pos,O));rows.add(new ExactLinearProgram.Constraint(neg,O.negate()));}if(n>15){t--;continue;}for(var cap:caps)rows.add(new ExactLinearProgram.Constraint(cap,O));BigInteger[]lo=new BigInteger[n],hi=new BigInteger[n];Arrays.fill(lo,Z);Arrays.fill(hi,O);var solutions=values(n,2).stream().filter(x->valid(rows,x)).toList();var b=b();var journal=new CountProof.Journal(32L<<20);b.proofJournal(journal);try(var p=new CountHall(rows,lo,hi,b)){while(!p.step()){}hallCuts+=p.cuts().size();for(var x:solutions)if(!valid(p.cuts(),x))throw new AssertionError("Hall false cut "+t);}proofs(journal);if(b.reservedBytes()!=0)throw new AssertionError("Hall leak");}
 if(hc==0||rc==0||hallCuts==0||softSolved==0)throw new AssertionError("unexercised mechanism");System.out.println("PASS Hermite 1000 cuts="+hc+" reduced-cost 1000 cuts="+rc+" LRB="+lr+" core-soft witnesses="+softSolved+"/500 Hall 600 cuts="+hallCuts);
 }
}
