package org.cgse.core;
import java.math.BigInteger;import java.util.*;import java.util.concurrent.atomic.AtomicInteger;
public class LpCutSafetyProbe{
 static BigInteger b(long x){return BigInteger.valueOf(x);}static long cutCount,points,models,nulls;
 static boolean valid(ExactLinearProgram.Constraint r,BigInteger[]x){BigInteger sum=BigInteger.ZERO;for(var e:r.terms().entrySet())sum=sum.add(e.getValue().multiply(x[e.getKey()]));return sum.compareTo(r.upper())<=0;}
 static BigInteger[] fill(int n,long v){var a=new BigInteger[n];Arrays.fill(a,b(v));return a;}
 public static void main(String[] args){System.setProperty("lp.normalize","true");Random rnd=new Random(61993489);for(int test=0;test<6000;test++){int n=2+rnd.nextInt(8),m=2+rnd.nextInt(18);var lo=fill(n,0);var hi=fill(n,1);int plant=rnd.nextInt(1<<n);List<ExactLinearProgram.Constraint> rows=new ArrayList<>();for(int r=0;r<m;r++){Map<Integer,BigInteger> terms=new TreeMap<>();BigInteger factor=r%3==0?BigInteger.TEN.pow(35):test%9==0?BigInteger.TEN.pow(70):BigInteger.ONE;BigInteger rhs=b(rnd.nextInt(9)-(test%4==0?6:0)).multiply(factor);for(int i=0;i<n;i++){int a=rnd.nextInt(21)-10;if(a!=0){BigInteger c=b(a).multiply(factor);terms.put(i,c);if(test%4!=0&&(plant&(1<<i))!=0)rhs=rhs.add(c);}}rows.add(new ExactLinearProgram.Constraint(terms,rhs));}for(int i=0;i<n;i++)if(rnd.nextInt(4)==0)lo[i]=hi[i]=b(rnd.nextInt(2));PlanningBudget budget=new PlanningBudget(0,2_000_000,64L<<20,()->false,()->0L);var result=CountLpLearning.solve(rows,lo,hi,budget,200000);models++;if(result==null)nulls++;else{cutCount+=result.cuts().size();for(int mask=0;mask<(1<<n);mask++){BigInteger[]x=fill(n,0);for(int i=0;i<n;i++)if((mask&(1<<i))!=0)x[i]=BigInteger.ONE;if(rows.stream().anyMatch(r->!valid(r,x)))continue;points++;for(var cut:result.cuts())if(!valid(cut,x))throw new AssertionError("cut not global test="+test+" localLow="+Arrays.toString(lo)+" localHi="+Arrays.toString(hi)+" cut="+cut+" original feasible="+Arrays.toString(x));}}if(budget.reservedBytes()!=0)throw new AssertionError("leak model="+test);}
  for(int kind=0;kind<5;kind++){var lo=fill(3,0);var hi=fill(3,1);if(kind==0)lo[0]=b(-1);if(kind==1)hi[0]=b(2);if(kind==2)lo[0]=hi[0]=BigInteger.TEN.pow(70);if(kind==3)hi[0]=null;if(kind==4)Arrays.fill(lo,BigInteger.ONE);var budget=new PlanningBudget(0,10000,1024,()->false,()->0L);var got=CountLpLearning.solve(List.of(new ExactLinearProgram.Constraint(Map.of(0,b(1)),b(0))),lo,hi,budget,10000);if(got!=null||budget.reservedBytes()!=0)throw new AssertionError("unsupported kind="+kind);}
  List<ExactLinearProgram.Constraint> rows=new ArrayList<>();for(int r=0;r<40;r++){Map<Integer,BigInteger> terms=new TreeMap<>();for(int i=0;i<20;i++)terms.put(i,b((i+r)%19-9));rows.add(new ExactLinearProgram.Constraint(terms,b(r%8-2)));}
  for(int after:new int[]{0,1,10,100})for(long mem:new long[]{1024,8192,65536,1048576}){AtomicInteger calls=new AtomicInteger();var budget=new PlanningBudget(0,100000,mem,()->calls.incrementAndGet()>after,()->0L);try{CountLpLearning.solve(rows,fill(20,0),fill(20,1),budget,32768);}catch(java.util.concurrent.CancellationException|PlanningBudget.Exhausted expected){}if(budget.reservedBytes()!=0)throw new AssertionError("cancel leak");}
  for(long cap:new long[]{1,17,64,1024,8192}){var budget=new PlanningBudget(0,cap,1L<<20,()->false,()->0L);try{CountLpLearning.solve(rows,fill(20,0),fill(20,1),budget,32768);}catch(PlanningBudget.Exhausted expected){}if(budget.reservedBytes()!=0)throw new AssertionError("budget leak");}
  var budget=new PlanningBudget(0,100000,1024,()->false,()->0L);var result=CountLpLearning.solve(rows,fill(20,0),fill(20,1),budget,32768);System.out.println("tinyMemory result="+(result==null?"null":"result")+" work="+budget.nodes()+" peak="+budget.peakBytes()+" reserved="+budget.reservedBytes());
  System.out.println("LpCutSafetyProbe models="+models+" cuts="+cutCount+" globallyFeasiblePoints="+points+" null="+nulls+" invalid=0 ownedLeaks=0 unsupported=5 cancellation=16 budgets=5");
 }
}
