package org.cgse.core;
import java.math.BigInteger;import java.util.*;import java.util.concurrent.atomic.AtomicBoolean;
public class CoverFairProbe{
 static BigInteger b(long v){return BigInteger.valueOf(v);}static long points,totalCuts,certificates;static BigInteger[] fill(int n,int v){BigInteger[] x=new BigInteger[n];Arrays.fill(x,b(v));return x;}
 static boolean pass(ExactLinearProgram.Constraint row,BigInteger[] x){BigInteger z=BigInteger.ZERO;for(var e:row.terms().entrySet())z=z.add(e.getValue().multiply(x[e.getKey()]));return z.compareTo(row.upper())<=0;}
 static List<ExactLinearProgram.Constraint> run(List<ExactLinearProgram.Constraint> rows,BigInteger[] lo,BigInteger[] hi,ExactRational[] point){PlanningBudget budget=new PlanningBudget(0,20_000_000,64L<<20,()->false,()->0L);CountProof.Journal journal=new CountProof.Journal(32L<<20);budget.proofJournal(journal);List<ExactLinearProgram.Constraint> cuts;try(var s=new CountCoverCuts(rows,lo,hi,point,budget)){while(!s.step()){}cuts=s.cuts();}if(budget.reservedBytes()!=0||cuts.size()>8)throw new AssertionError("resource leak/cap");for(var p:journal.entries()){certificates++;if(CountProof.verify(p,20_000_000)!=CountProof.Verdict.VERIFIED)throw new AssertionError("invalid certificate");}for(var p:journal.knapsacks()){certificates++;if(CountProof.verify(p,20_000_000)!=CountProof.Verdict.VERIFIED)throw new AssertionError("invalid lift");}return cuts;}
 public static void main(String[] args){Random random=new Random(15392172);for(int c=0;c<1200;c++){int active=2+random.nextInt(8),n=c%2==0?89:active;var lo=fill(n,0);var hi=fill(n,1);int planted=random.nextInt(1<<active);ExactRational[] point=new ExactRational[n];for(int i=0;i<n;i++)point[i]=new ExactRational(b(random.nextInt(5)),b(4));List<ExactLinearProgram.Constraint> rows=new ArrayList<>();int m=c%2==0?160:15;BigInteger scale=c%7==0?BigInteger.TEN.pow(40):BigInteger.ONE;for(int k=0;k<m;k++){Map<Integer,BigInteger> terms=new TreeMap<>();BigInteger rhs=b(random.nextInt(25)-(c%2==0?0:5)).multiply(scale);for(int i=0;i<active;i++){int a=random.nextInt(15)-7;if(a!=0){terms.put(i,b(a).multiply(scale));if(c%2==0&&(planted&(1<<i))!=0)rhs=rhs.add(b(a).multiply(scale));}}rows.add(new ExactLinearProgram.Constraint(terms,rhs));}var cuts=run(rows,lo,hi,point);totalCuts+=cuts.size();for(int mask=0;mask<(1<<active);mask++){var x=lo.clone();for(int i=0;i<active;i++)if((mask&(1<<i))!=0)x[i]=BigInteger.ONE;if(rows.stream().anyMatch(r->!pass(r,x)))continue;points++;for(var cut:cuts)if(!pass(cut,x))throw new AssertionError("bad cut c="+c+" "+cut);}}
  List<ExactLinearProgram.Constraint> rows=new ArrayList<>();var lo=fill(89,0);var hi=fill(89,1);ExactRational[] point=new ExactRational[89];Arrays.fill(point,new ExactRational(b(3),b(5)));for(int r=0;r<24;r++){Map<Integer,BigInteger> terms=new TreeMap<>();BigInteger total=BigInteger.ZERO;for(int i=0;i<87;i++){int w=1+(i+r)%89;terms.put(i,b(w));total=total.add(b(w));}BigInteger cap=total.multiply(b(3)).add(b(4)).divide(b(5));rows.add(new ExactLinearProgram.Constraint(terms,cap));}var late=new ExactLinearProgram.Constraint(Map.of(87,b(2),88,b(2)),b(3));rows.add(late);var want=new ExactLinearProgram.Constraint(Map.of(87,b(1),88,b(1)),b(1));var tail=run(rows,lo,hi,point);System.out.println("lateFound="+tail.contains(want)+" cuts="+tail.size());if(args.length==0&&!tail.contains(want))throw new AssertionError("late cover starved");
  for(int stop:new int[]{0,1,3,10})for(long mem:new long[]{1024,65536,1048576}){AtomicBoolean cancel=new AtomicBoolean();PlanningBudget budget=new PlanningBudget(0,20_000_000,mem,cancel::get,()->0L);try(var search=new CountCoverCuts(rows,lo,hi,point,budget)){for(int i=0;i<stop&&!search.step();i++){}cancel.set(true);while(!search.step()){}search.close();}catch(java.util.concurrent.CancellationException|PlanningBudget.Exhausted expected){}if(budget.reservedBytes()!=0)throw new AssertionError("cancel leak");}
  System.out.println("CoverFairProbe models=1200 cuts="+totalCuts+" feasibleIntegerPoints="+points+" certificates="+certificates+" invalid=0 ownedLeaks=0");
 }
}
